package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_COMPANY
{
    public static final String ID = "Company";

    public static class B_COMPANIES
    {
        public static final String ID                    = "Companies";
        public static final String I_POST_CODE           = "postCode";
        public static final String I_ADDRESS_LINE_2      = "addressLine2";
        public static final String I_BANK_ADDRESS_LINE_2 = "bankAddressLine2";
        public static final String I_ACCOUNT_NUMBER      = "accountNumber";
        public static final String I_ADDRESS_LINE_1      = "addressLine1";
        public static final String I_BANK_ADDRESS_LINE_1 = "bankAddressLine1";
        public static final String I_BANK_POST_CODE      = "bankPostCode";
        public static final String I_IBAN                = "iban";
        public static final String I_ID                  = "id";
        public static final String I_ADDRESS_LINE_3      = "addressLine3";
        public static final String I_USER_ID             = "userId";
        public static final String I_BANK_TOWN           = "bankTown";
        public static final String I_NAME                = "name";
        public static final String I_TOWN                = "town";
        public static final String I_COUNTRY             = "country";
        public static final String I_BANK_NAME           = "bankName";
        public static final String I_BANK_COUNTRY        = "bankCountry";
        public static final String I_VAT_NR              = "vatNr";
        public static final String I_BANK_ADDRESS_LINE_3 = "bankAddressLine3";
        public static final String I_SHOW_BANK           = "showBank";
        public static final String I_VAT_NR_LABEL        = "vatNrLabel";

    }

    public static class B_COMPANIES_DETAIL
    {
        public static final String ID                    = "CompaniesDetail";
        public static final String I_POST_CODE           = "postCode";
        public static final String I_ADDRESS_LINE_2      = "addressLine2";
        public static final String I_BANK_ADDRESS_LINE_2 = "bankAddressLine2";
        public static final String I_ACCOUNT_NUMBER      = "accountNumber";
        public static final String I_ADDRESS_LINE_1      = "addressLine1";
        public static final String I_BANK_ADDRESS_LINE_1 = "bankAddressLine1";
        public static final String I_BANK_POST_CODE      = "bankPostCode";
        public static final String I_IBAN                = "iban";
        public static final String I_ID                  = "id";
        public static final String I_ADDRESS_LINE_3      = "addressLine3";
        public static final String I_USER_ID             = "userId";
        public static final String I_BANK_TOWN           = "bankTown";
        public static final String I_BANK_COUNTRY        = "bankCountry";
        public static final String I_NAME                = "name";
        public static final String I_TOWN                = "town";
        public static final String I_BANK_NAME           = "bankName";
        public static final String I_VAT_NR              = "vatNr";
        public static final String I_BANK_ADDRESS_LINE_3 = "bankAddressLine3";
        public static final String I_COUNTRY             = "country";
        public static final String I_COMPANY_INFO_LABEL  = "companyInfoLabel";
        public static final String I_BANK_INFO_LABEL     = "bankInfoLabel";
        public static final String I_VAT_NR_LABEL        = "vatNrLabel";

    }

    public static final String C_COMPANIES            = "Companies";
    public static final String C_COMPANY_DETAIL_POPUP = "CompanyDetailPopup";
    public static final String C_COMPANY_DETAIL       = "CompanyDetail";

    public static final String AC_SHOW_BANK_DETAILS   = "SHOW_BANK_DETAILS";

}