package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_INVOICE
{
    public static final String ID = "Invoice";

    public static class B_INVOICE
    {
        public static final String ID                = "Invoice";
        public static final String I_NR              = "nr";
        public static final String I_AMOUNT_EXCL_VAT = "amountExclVat";
        public static final String I_AMOUNT_INCL_VAT = "amountInclVat";
        public static final String I_ID              = "id";
        public static final String I_INV_DATE        = "invDate";
        public static final String I_USER_ID         = "userId";
        public static final String I_CONF_ID         = "confId";
        public static final String I_PAYINF_ID       = "payinfId";
        public static final String I_PRINTED         = "printed";
        public static final String I_INVOICE_ID      = "invoiceId";
        public static final String I_CUST_ID         = "custId";
        public static final String I_PAID            = "paid";

    }

    public static class B_INVOICE_POSITIONS
    {
        public static final String ID             = "InvoicePositions";
        public static final String I_HOURS_WORKED = "hoursWorked";
        public static final String I_USER_ID      = "userId";
        public static final String I_POSITION     = "position";
        public static final String I_DESCRIPTION  = "description";
        public static final String I_CUPR_ID      = "cuprId";
        public static final String I_ID           = "id";
        public static final String I_INV_ID       = "invId";
        public static final String I_VAT_ID       = "vatId";

    }

}