package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_MASTER_DATA
{
    public static final String ID = "MasterData";

    public static class B_CONTACT_TYPES
    {
        public static final String ID                  = "ContactTypes";
        public static final String I_TYPE              = "type";
        public static final String I_ID                = "id";
        public static final String I_USER_ID           = "userId";
        public static final String I_DESCRIPTION       = "description";
        public static final String I_TYPE_LABEL        = "typeLabel";
        public static final String I_DESCRIPTION_LABEL = "descriptionLabel";

    }

    public static class B_PAYMENT_TERMS
    {
        public static final String ID              = "PaymentTerms";
        public static final String I_ID            = "id";
        public static final String I_USER_ID       = "userId";
        public static final String I_PAYMENT_TERMS = "paymentTerms";

    }

    public static final String C_PAGES         = "pages";
    public static final String C_CONTACT_TYPES = "ContactTypes";
    public static final String C_PAYMENT_TERMS = "PaymentTerms";

}