package org.entirej.ejinvoice.forms.constants;

/*
 * AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the entirej plugin from the form.
 * It should not be modified by hand.
 */
public class F_MASTER_DATA
{
    public static final String ID = "MasterData";

    public static class B_CONTACT_TYPES
    {
        public static final String ID                  = "ContactTypes";
        public static final String I_TYPE              = "type";
        public static final String I_ID                = "id";
        public static final String I_USER_ID           = "userId";
        public static final String I_DESCRIPTION       = "description";
        public static final String I_TYPE_LABEL        = "typeLabel";
        public static final String I_DESCRIPTION_LABEL = "descriptionLabel";

    }

    public static class B_PAYMENT_TERMS
    {
        public static final String ID              = "PaymentTerms";
        public static final String I_ID            = "id";
        public static final String I_USER_ID       = "userId";
        public static final String I_PAYMENT_TERMS = "paymentTerms";

    }

    public static class B_VAT_RATES
    {
        public static final String ID           = "VatRates";
        public static final String I_USER_ID    = "userId";
        public static final String I_RATE       = "rate";
        public static final String I_ID         = "id";
        public static final String I_NOTES      = "notes";
        public static final String I_NAME       = "name";
        public static final String I_RATE_LABEL = "rateLabel";
        public static final String I_NAME_LABEL = "nameLabel";

    }

    public static class B_SALUTATIONS
    {
        public static final String ID            = "Salutations";
        public static final String I_VALUE       = "value";
        public static final String I_ID          = "id";
        public static final String I_USER_ID     = "userId";
        public static final String I_VALUE_LABEL = "valueLabel";

    }

    public static final String C_FORMS = "forms";

    public static class C_FORMS_PAGES
    {
        public static final String CONTACT_TYPES = "ContactTypes";
        public static final String PAYMENT_TERMS = "PaymentTerms";
        public static final String VAT_RATES     = "VatRates";
        public static final String SALUTATIONS   = "Salutations";

    }

    public static final String C_CONTACT_TYPES = "ContactTypes";
    public static final String C_PAYMENT_TERMS = "PaymentTerms";
    public static final String C_VAT_RATES     = "VatRates";
    public static final String C_SALUTATIONS   = "Salutations";

    public static final String AC_DELETE       = "DELETE";
    public static final String AC_EDIT         = "EDIT";
    public static final String AC_NEW          = "NEW";

}