package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_PROJECT
{
    public static final String ID = "Project";

    public static class B_PROJECTS
    {
        public static final String ID               = "Projects";
        public static final String I_ID             = "id";
        public static final String I_DESCRIPTION    = "description";
        public static final String I_NAME           = "name";
        public static final String I_PAY_RATE       = "payRate";
        public static final String I_USER_ID        = "userId";
        public static final String I_CUSTOMER_ID    = "customerId";
        public static final String I_PAY_RATE_LABEL = "payRateLabel";
        public static final String I__DETAILS       = "_details";

    }

    public static class L_CUSTOMERS
    {
        public static final String ID               = "Customers";
        public static final String I_USER_ID        = "userId";
        public static final String I_ID             = "id";
        public static final String I_ADDRESS_LINE_1 = "addressLine1";
        public static final String I_ADDRESS_LINE_2 = "addressLine2";
        public static final String I_NAME           = "name";
        public static final String I_POST_CODE      = "postCode";
        public static final String I_ADDRESS_LINE_3 = "addressLine3";
        public static final String I_TOWN           = "town";
        public static final String I_COUNTRY        = "country";

    }

    public static final String C_PROJECTS = "Projects";

    public static final String AC_DELETE  = "DELETE";
    public static final String AC_EDIT    = "EDIT";
    public static final String AC_NEW     = "NEW";

}