package org.entirej.ejinvoice.forms.invoice.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_RRR
{
    public static final String ID = "rrr";

    public static class B_RRRR
    {
        public static final String ID = "rrrr";

    }

    public static final String C_RRRR = "rrrr";

}