package org.entirej.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the EntireJReportProperties.  It
 * should not be modified by hand.
 */
public class EJ_REPORT_PROPERTIES
{

    public static final String P_USER_ID         = "USER_ID";

    public static final String VA_HEADER_TITLE   = "HEADER_TITLE";
    public static final String VA_BOLD_TEXT      = "BOLD_TEXT";
    public static final String VA_LINE_BG        = "LINE_BG";
    public static final String VA_TABLE_EVEN_ROW = "TABLE_EVEN_ROW";
    public static final String VA_LABEL_BG       = "LABEL_BG";

}