package org.entirej.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the EntireJProperties.  It
 * should not be modified by hand.
 */
public class EJ_PROPERTIES {
	public static final String M_DEFAULT = "Default";

	public static final String P_USER = "USER";
	public static final String P_EMAIL = "email";
	public static final String P_NAME = "name";
	public static final String P_USER_ID = "USER_ID";
	public static final String P_COMPANY_ID = "COMPANY_ID";
	public static final String P_BUILT_BY = "builtBy";
	public static final String P_DATABASE_NAME = "DATABASE_NAME";
	public static final String P_DATA_SOURCE_NAME = "dataSourceName";
	public static final String P_NEW_COMPANY_DEFAULTS_COMPANY_ID = "newCompanyDefaultsCompanyId";

	public static final String VA_DATA = "data";
	public static final String VA_DATA_BOLD = "dataBold";
	public static final String VA_TITLE_LARGE = "titleLarge";
	public static final String VA_TITLE_MEDIUM = "titleMedium";
	public static final String VA_TITLE_SMALL = "titleSmall";
	public static final String VA_DATA_PAID = "dataPaid";
	public static final String VA_DATA_DRAFT = "dataDraft";
	public static final String VA_DATA_OVERDUE = "dataOverdue";
	public static final String VA_DATA_ODD = "dataOdd";
	public static final String VA_TABLE_HEADER = "tableHeader";
	public static final String VA_DATA_SMALL = "dataSmall";
	public static final String VA_DATA_SMALL_BOLD = "dataSmallBold";
	public static final String VA_WORKWEEK_HEADER_VA = "WORKWEEK_HEADER_VA";
	public static final String VA_WORKWEEK_DATA_ODD = "WORKWEEK_DATA_ODD";
	public static final String VA_DATA_EVEN = "dataEven";
	public static final String VA_TABLE_HEADER_2 = "tableHeader2";
	public static final String VA_DATA_GRAY = "dataGray";
	public static final String VA_INVOIEC_STATUS_DRAFT = "InvoiecStatusDraft";
	public static final String VA_INVOICE_STATUS_LATE = "InvoiceStatusLate";
	public static final String VA_INVOICE_STATUS_SENT = "InvoiceStatusSent";
	public static final String VA_INVOICE_STATUS_PAID = "InvoiceStatusPaid";

}