package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_CONTACT_TYPES
{
    public static final String ID = "ContactTypes";

    public static class B_CONTACT_TYPES_TOOLBAR
    {
        public static final String ID                     = "ContactTypesToolbar";
        public static final String I_ADD_NEW_CONTACT_TYPE = "addNewContactType";

    }

    public static class B_CONTACT_TYPES
    {
        public static final String ID             = "ContactTypes";
        public static final String I_TYPE         = "type";
        public static final String I_ID           = "id";
        public static final String I_DESCRIPTION  = "description";
        public static final String I_COMPANY_ID   = "companyId";
        public static final String I_EDIT         = "edit";
        public static final String I_DELETE       = "delete";
        public static final String I_DISPLAY_TEXT = "displayText";

    }

    public static class B_CONTACT_TYPES_UPDATE
    {
        public static final String ID            = "ContactTypesUpdate";
        public static final String I_TYPE        = "type";
        public static final String I_TYPE_ERROR  = "typeError";
        public static final String I_DESCRIPTION = "description";
        public static final String I_PAGE_TITLE  = "pageTitle";
        public static final String I_SAVE        = "save";
        public static final String I_CANCEL      = "cancel";
        public static final String I_ID          = "id";

    }

    public static class B_CONTACT_TYPES_INSERT
    {
        public static final String ID            = "ContactTypesInsert";
        public static final String I_TYPE        = "type";
        public static final String I_TYPE_ERROR  = "typeError";
        public static final String I_DESCRIPTION = "description";
        public static final String I_PAGE_TITLE  = "pageTitle";
        public static final String I_SAVE        = "save";
        public static final String I_CANCEL      = "cancel";

    }

    public static final String C_MAIN_STACK = "mainStack";

    public static class C_MAIN_STACK_PAGES
    {
        public static final String MAIN   = "main";
        public static final String EDIT   = "edit";
        public static final String INSERT = "insert";

    }

    public static final String C_CONTACT_TYPES_TOOLBAR = "ContactTypesToolbar";
    public static final String C_CONTACT_TYPES         = "ContactTypes";
    public static final String C_CONTACT_TYPES_UPDATE  = "ContactTypesUpdate";
    public static final String C_CONTACT_TYPES_INSERT  = "ContactTypesInsert";

    public static final String AC_CREATE_CONTACT_TYPE  = "CREATE_CONTACT_TYPE";
    public static final String AC_DELETE_CONTACT_TYPE  = "DELETE_CONTACT_TYPE";
    public static final String AC_EDIT_CANCEL          = "EDIT_CANCEL";
    public static final String AC_EDIT_SAVE            = "EDIT_SAVE";
    public static final String AC_INSERT_CANCEL        = "INSERT_CANCEL";
    public static final String AC_INSERT_SAVE          = "INSERT_SAVE";
    public static final String AC_MODIFY_CONTACT       = "MODIFY_CONTACT";

    public static final String P_IN_EDIT_MODE          = "IN_EDIT_MODE";

}