package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_COMPANY
{
    public static final String ID = "Company";

    public static class B_COMPANIES_TOOLBAR
    {
        public static final String ID             = "CompaniesToolbar";
        public static final String I_EDIT_COMPANY = "editCompany";

    }

    public static class B_COMPANIES
    {
        public static final String ID                     = "Companies";
        public static final String I_POST_CODE            = "postCode";
        public static final String I_ADDRESS              = "address";
        public static final String I_ID                   = "id";
        public static final String I_NAME                 = "name";
        public static final String I_TOWN                 = "town";
        public static final String I_VAT_NR               = "vatNr";
        public static final String I_COUNTRY              = "country";
        public static final String I_LOGO                 = "logo";
        public static final String I_INVOICE_SUMMARY      = "invoiceSummary";
        public static final String I_INVOICE_NOTES        = "invoiceNotes";
        public static final String I_INVOICE_NOTES_INFO   = "invoiceNotesInfo";
        public static final String I_INVOICE_SUMMARY_INFO = "invoiceSummaryInfo";

    }

    public static class B_USER_TOOLBAR
    {
        public static final String ID                = "UserToolbar";
        public static final String I_CREATE_NEW_USER = "createNewUser";

    }

    public static class B_USERS
    {
        public static final String ID                 = "Users";
        public static final String I_FIRST_NAME       = "firstName";
        public static final String I_LAST_NAME        = "lastName";
        public static final String I_LOCALE_LANGUAGE  = "localeLanguage";
        public static final String I_LOCALE_COUNTRY   = "localeCountry";
        public static final String I_NOTES            = "notes";
        public static final String I_ID               = "id";
        public static final String I_TOWN             = "town";
        public static final String I_COMPANY_ID       = "companyId";
        public static final String I_EMAIL            = "email";
        public static final String I_POST_CODE        = "postCode";
        public static final String I_ADDRESS          = "address";
        public static final String I_PASSWORD         = "password";
        public static final String I_LOCALE           = "locale";
        public static final String I_ROLE             = "role";
        public static final String I_EDIT             = "edit";
        public static final String I_DELETE           = "delete";
        public static final String I_INITIAL_PASSWORD = "initialPassword";
        public static final String I_CONFIRM_PASSWORD = "confirmPassword";
        public static final String I_CONFIRM_EMAIL    = "confirmEmail";
        public static final String I_CHANGE_EMAIL     = "changeEmail";
        public static final String I_CHANGE_PASSWORD  = "changePassword";
        public static final String I_ACTIVE           = "active";

    }

    public static class L_LOCALES
    {
        public static final String ID              = "Locales";
        public static final String I_LANGUAGE      = "language";
        public static final String I_COUNTRY       = "country";
        public static final String I_LOCALE        = "locale";
        public static final String I_LANGUAGE_DESC = "languageDesc";
        public static final String I_COUNTRY_DESC  = "countryDesc";
        public static final String I_CCY_CODE      = "ccyCode";

    }

    public static final String C_COMPANY_TOOLBAR       = "CompanyToolbar";
    public static final String C_COMPANIES             = "Companies";
    public static final String C_EMPLOYEE              = "employee";
    public static final String C_USER_TOOLBAR          = "UserToolbar";
    public static final String C_USERS                 = "Users";

    public static final String AC_ADD_LOGO             = "ADD_LOGO";
    public static final String AC_CHANGE_EMAIL         = "CHANGE_EMAIL";
    public static final String AC_CHANGE_PASSWORD      = "CHANGE_PASSWORD";
    public static final String AC_CREATE_NEW_USER      = "CREATE_NEW_USER";
    public static final String AC_DELETE_USER          = "DELETE_USER";
    public static final String AC_EDIT_COMPANY_DETAILS = "EDIT_COMPANY_DETAILS";
    public static final String AC_EDIT_USER            = "EDIT_USER";

}