package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_COMPANY
{
    public static final String ID = "Company";

    public static class B_COMPANIES
    {
        public static final String ID                     = "Companies";
        public static final String I_POST_CODE            = "postCode";
        public static final String I_ADDRESS              = "address";
        public static final String I_ID                   = "id";
        public static final String I_NAME                 = "name";
        public static final String I_TOWN                 = "town";
        public static final String I_VAT_NR               = "vatNr";
        public static final String I_COUNTRY              = "country";
        public static final String I_LOGO                 = "logo";
        public static final String I_INVOICE_SUMMARY      = "invoiceSummary";
        public static final String I_INVOICE_FOOTER       = "invoiceFooter";
        public static final String I_INVOICE_FOOTER_INFO  = "invoiceFooterInfo";
        public static final String I_INVOICE_SUMMARY_INFO = "invoiceSummaryInfo";

    }

    public static class B_COMPANIES_EDIT
    {
        public static final String ID                          = "CompaniesEdit";
        public static final String I_ID                        = "id";
        public static final String I_PAGE_TITLE                = "pageTitle";
        public static final String I_INVOICE_INFORMATION_TITLE = "invoiceInformationTitle";
        public static final String I_COMPANY_LOGO_TITLE        = "companyLogoTitle";
        public static final String I_NAME                      = "name";
        public static final String I_NAME_ERROR                = "nameError";
        public static final String I_ADDRESS                   = "address";
        public static final String I_POST_CODE                 = "postCode";
        public static final String I_TOWN                      = "town";
        public static final String I_COUNTRY                   = "country";
        public static final String I_VAT_NR                    = "vatNr";
        public static final String I_INVOICE_SUMMARY           = "invoiceSummary";
        public static final String I_INVOICE_SUMMARY_INFO      = "invoiceSummaryInfo";
        public static final String I_INVOICE_FOOTER            = "invoiceFooter";
        public static final String I_INVOICE_INFORMATION_INFO  = "invoiceInformationInfo";
        public static final String I_LOGO                      = "logo";
        public static final String I_SAVE                      = "save";
        public static final String I_ADD_LOGO                  = "addLogo";

    }

    public static class L_LOCALES
    {
        public static final String ID              = "Locales";
        public static final String I_LANGUAGE      = "language";
        public static final String I_COUNTRY       = "country";
        public static final String I_LOCALE        = "locale";
        public static final String I_LANGUAGE_DESC = "languageDesc";
        public static final String I_COUNTRY_DESC  = "countryDesc";
        public static final String I_CCY_CODE      = "ccyCode";

    }

    public static final String C_COMPANIES_EDIT = "CompaniesEdit";

    public static final String AC_ADD_LOGO      = "ADD_LOGO";
    public static final String AC_EDIT_SAVE     = "EDIT_SAVE";

    public static final String P_IN_EDIT_MODE   = "IN_EDIT_MODE";

}