package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_CUSTOMERS
{
    public static final String ID = "Customers";

    public static class B_CUSTOMERS_TOOLBAR
    {
        public static final String ID                        = "CustomersToolbar";
        public static final String I_CREATE_NEW_CUSTOMER     = "createNewCustomer";
        public static final String I_SHOW_INACTIVE_CUSTOMERS = "showInactiveCustomers";

    }

    public static class B_CUSTOMERS
    {
        public static final String ID                 = "Customers";
        public static final String I_COMPANY_ID       = "companyId";
        public static final String I_ID               = "id";
        public static final String I_ADDRESS          = "address";
        public static final String I_NAME             = "name";
        public static final String I_POST_CODE        = "postCode";
        public static final String I_TOWN             = "town";
        public static final String I_COUNTRY          = "country";
        public static final String I_EMAIL            = "email";
        public static final String I_PHONE            = "phone";
        public static final String I_CONTACT_TYPES_ID = "contactTypesId";
        public static final String I_SALUTATIONS_ID   = "salutationsId";
        public static final String I_CUSTOMER_ID      = "customerId";
        public static final String I_FIRST_NAME       = "firstName";
        public static final String I_LAST_NAME        = "lastName";
        public static final String I_MOBILE           = "mobile";
        public static final String I_VAT_ID           = "vatId";
        public static final String I_VAT_RATE         = "vatRate";
        public static final String I_PAYMENT_DAYS     = "paymentDays";
        public static final String I_DAYS_LABEL       = "daysLabel";
        public static final String I_CUSTOMER_NUMBER  = "customerNumber";
        public static final String I_EDIT             = "edit";
        public static final String I_DELETE           = "delete";
        public static final String I_CONTACTS         = "contacts";
        public static final String I_LOCALE           = "locale";
        public static final String I_LOCALE_COUNTRY   = "localeCountry";
        public static final String I_LOCALE_LANGUAGE  = "localeLanguage";
        public static final String I_CCY_CODE         = "ccyCode";
        public static final String I_ACTIVE           = "active";
        public static final String I_DISPLAY_TEXT     = "displayText";

    }

    public static class B_CUSTOMERS_KEY
    {
        public static final String ID               = "CustomersKey";
        public static final String I_CONTACTS       = "contacts";
        public static final String I_CONTACTS_LABEL = "contactsLabel";

    }

    public static class L_VAT_RATE
    {
        public static final String ID           = "VatRate";
        public static final String I_NOTES      = "notes";
        public static final String I_RATE       = "rate";
        public static final String I_NAME       = "name";
        public static final String I_ID         = "id";
        public static final String I_COMPANY_ID = "companyId";

    }

    public static class L_CUSTOMER
    {
        public static final String ID                 = "Customer";
        public static final String I_ID               = "id";
        public static final String I_ADDRESS          = "address";
        public static final String I_NAME             = "name";
        public static final String I_POST_CODE        = "postCode";
        public static final String I_TOWN             = "town";
        public static final String I_COUNTRY          = "country";
        public static final String I_COMPANY_ID       = "companyId";
        public static final String I_ITEMS_TO_INVOICE = "itemsToInvoice";

    }

    public static class L_CONTACT_TYPES
    {
        public static final String ID            = "ContactTypes";
        public static final String I_TYPE        = "type";
        public static final String I_ID          = "id";
        public static final String I_DESCRIPTION = "description";
        public static final String I_COMPANY_ID  = "companyId";

    }

    public static class L_SALUTATIONS
    {
        public static final String ID           = "Salutations";
        public static final String I_VALUE      = "value";
        public static final String I_ID         = "id";
        public static final String I_COMPANY_ID = "companyId";

    }

    public static class L_CUSTOMER_LOCALE
    {
        public static final String ID              = "CustomerLocale";
        public static final String I_LANGUAGE      = "language";
        public static final String I_COUNTRY       = "country";
        public static final String I_LOCALE        = "locale";
        public static final String I_LANGUAGE_DESC = "languageDesc";
        public static final String I_COUNTRY_DESC  = "countryDesc";
        public static final String I_CCY_CODE      = "ccyCode";

    }

    public static final String C_CUSTOMERS_TOOLBAR      = "CustomersToolbar";
    public static final String C_CUSTOMER               = "Customer";
    public static final String C_CUSTOMERS_KEY          = "CustomersKey";

    public static final String AC_CREATE_NEW_CUSTOMER   = "CREATE_NEW_CUSTOMER";
    public static final String AC_DELETE_CUSTOMER       = "DELETE_CUSTOMER";
    public static final String AC_EDIT_CUSTOMER         = "EDIT_CUSTOMER";
    public static final String AC_QUERY_CUSTOMERS       = "QUERY_CUSTOMERS";
    public static final String AC_SHOW_CUSTOMER_DETAILS = "SHOW_CUSTOMER_DETAILS";

}