package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_CUSTOMER_CONTACTS {
	public static final String ID = "CustomerContacts";

	public static class B_CUSTOMER_CONTACTS_TOOLBAR {
		public static final String ID = "CustomerContactsToolbar";
		public static final String I_ADD_NEW_CONTACT = "addNewContact";
		public static final String I_BACK_TO_CUSTOMER_LIST = "backToCustomerList";
		public static final String I_CUSTOMER_INFORMATION = "customerInformation";

	}

	public static class B_CUSTOMER_CONTACTS {
		public static final String ID = "CustomerContacts";
		public static final String I_EMAIL = "email";
		public static final String I_PHONE = "phone";
		public static final String I_CONTACT_TYPES_ID = "contactTypesId";
		public static final String I_CUSTOMER_ID = "customerId";
		public static final String I_ID = "id";
		public static final String I_FIRST_NAME = "firstName";
		public static final String I_SALUTATIONS_ID = "salutationsId";
		public static final String I_LAST_NAME = "lastName";
		public static final String I_MOBILE = "mobile";
		public static final String I_DELETE = "delete";
		public static final String I_EDIT = "edit";
		public static final String I_COMPANY_ID = "companyId";

	}

	public static class L_CONTACT_TYPES {
		public static final String ID = "ContactTypes";
		public static final String I_TYPE = "type";
		public static final String I_ID = "id";
		public static final String I_DESCRIPTION = "description";
		public static final String I_COMPANY_ID = "companyId";

	}

	public static class L_SALUTATIONS {
		public static final String ID = "Salutations";
		public static final String I_VALUE = "value";
		public static final String I_ID = "id";
		public static final String I_COMPANY_ID = "companyId";

	}

	public static class L_VAT {
		public static final String ID = "vat";
		public static final String I_NOTES = "notes";
		public static final String I_RATE = "rate";
		public static final String I_NAME = "name";
		public static final String I_ID = "id";
		public static final String I_COMPANY_ID = "companyId";

	}

	public static final String C_CUSTOMER_CONTACTS_TOOLBAR = "CustomerContactsToolbar";
	public static final String C_CUSTOMER_CONTACTS = "CustomerContacts";

	public static final String AC_ADD_NEW_CONTACT = "ADD_NEW_CONTACT";
	public static final String AC_BACK_TO_CUSTOMER_LIST = "BACK_TO_CUSTOMER_LIST";
	public static final String AC_DELETE_CUSTOMER_CONTACT = "DELETE_CUSTOMER_CONTACT";
	public static final String AC_EDIT_CONTACT = "EDIT_CONTACT";
	public static final String AC_OPEN_EMAIL = "OPEN_EMAIL";

	public static final String P_CST_ID = "cstId";
	public static final String P_CUSTOMER_INFORMATION = "customerInformation";

}