package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_CUSTOMER_CONTACTS
{
    public static final String ID = "CustomerContacts";

    public static class B_CUSTOMER_CONTACTS_TOOLBAR
    {
        public static final String ID                = "CustomerContactsToolbar";
        public static final String I_ADD_NEW_CONTACT = "addNewContact";
        public static final String I_CUSTOMER_ID     = "customerId";

    }

    public static class B_CUSTOMER_CONTACTS
    {
        public static final String ID                 = "CustomerContacts";
        public static final String I_EMAIL            = "email";
        public static final String I_PHONE            = "phone";
        public static final String I_CONTACT_TYPES_ID = "contactTypesId";
        public static final String I_CUSTOMER_ID      = "customerId";
        public static final String I_ID               = "id";
        public static final String I_FIRST_NAME       = "firstName";
        public static final String I_SALUTATIONS_ID   = "salutationsId";
        public static final String I_LAST_NAME        = "lastName";
        public static final String I_MOBILE           = "mobile";
        public static final String I_DELETE           = "delete";
        public static final String I_EDIT             = "edit";
        public static final String I_COMPANY_ID       = "companyId";
        public static final String I_CUSTOMER_NAME    = "customerName";
        public static final String I_DISPLAY_TEXT     = "displayText";
        public static final String I_SALUTATION       = "salutation";
        public static final String I_CONTACT_TYPE     = "contactType";

    }

    public static class B_CUSTOMER_CONTACTS_EDIT
    {
        public static final String ID                       = "CustomerContactsEdit";
        public static final String I_UPDATE_PAGE_TITLE      = "updatePageTitle";
        public static final String I_CONTACT_TYPES_ID       = "contactTypesId";
        public static final String I_CONTACT_TYPES_VALUE    = "contactTypesValue";
        public static final String I_CONTACT_TYPES_ID_ERROR = "contactTypesIdError";
        public static final String I_SALUTATIONS_ID         = "salutationsId";
        public static final String I_SALUTATIONS_ID_VALUE   = "salutationsIdValue";
        public static final String I_SALUTATIONS_ID_ERROR   = "salutationsIdError";
        public static final String I_FIRST_NAME             = "firstName";
        public static final String I_FIRST_NAME_ERROR       = "firstNameError";
        public static final String I_LAST_NAME              = "lastName";
        public static final String I_LAST_NAME_ERROR        = "lastNameError";
        public static final String I_PHONE                  = "phone";
        public static final String I_PHONE_ERROR            = "phoneError";
        public static final String I_MOBILE                 = "mobile";
        public static final String I_MOBILE_ERROR           = "mobileError";
        public static final String I_EMAIL                  = "email";
        public static final String I_EMAIL_ERROR            = "emailError";
        public static final String I_SAVE_BUTTON            = "saveButton";
        public static final String I_CANCEL_BUTTON          = "cancelButton";

    }

    public static class B_CUSTOMER_CONTACTS_INSERT
    {
        public static final String ID                       = "CustomerContactsInsert";
        public static final String I_INSERT_PAGE_TITLE      = "insertPageTitle";
        public static final String I_CONTACT_TYPES_ID       = "contactTypesId";
        public static final String I_CONTACT_TYPES_VALUE    = "contactTypesValue";
        public static final String I_CONTACT_TYPES_ID_ERROR = "contactTypesIdError";
        public static final String I_SALUTATIONS_ID         = "salutationsId";
        public static final String I_SALUTATIONS_ID_VALUE   = "salutationsIdValue";
        public static final String I_SALUTATIONS_ID_ERROR   = "salutationsIdError";
        public static final String I_FIRST_NAME             = "firstName";
        public static final String I_FIRST_NAME_ERROR       = "firstNameError";
        public static final String I_LAST_NAME              = "lastName";
        public static final String I_LAST_NAME_ERROR        = "lastNameError";
        public static final String I_PHONE                  = "phone";
        public static final String I_PHONE_ERROR            = "phoneError";
        public static final String I_MOBILE                 = "mobile";
        public static final String I_MOBILE_ERROR           = "mobileError";
        public static final String I_EMAIL                  = "email";
        public static final String I_EMAIL_ERROR            = "emailError";
        public static final String I_SAVE_BUTTON            = "saveButton";
        public static final String I_CANCEL_BUTTON          = "cancelButton";
        public static final String I_CUSTOMER_ID            = "customerId";
        public static final String I_CUSTOMER_ID_ERROR      = "customerIdError";
        public static final String I_CUSTOMER_NAME          = "customerName";

    }

    public static class L_CONTACT_TYPES
    {
        public static final String ID            = "ContactTypes";
        public static final String I_TYPE        = "type";
        public static final String I_ID          = "id";
        public static final String I_DESCRIPTION = "description";
        public static final String I_COMPANY_ID  = "companyId";

    }

    public static class L_SALUTATIONS
    {
        public static final String ID           = "Salutations";
        public static final String I_VALUE      = "value";
        public static final String I_ID         = "id";
        public static final String I_COMPANY_ID = "companyId";

    }

    public static class L_VAT
    {
        public static final String ID           = "vat";
        public static final String I_NOTES      = "notes";
        public static final String I_RATE       = "rate";
        public static final String I_NAME       = "name";
        public static final String I_ID         = "id";
        public static final String I_COMPANY_ID = "companyId";

    }

    public static class L_CUSTOMER_INFORMATION
    {
        public static final String ID                 = "CustomerInformation";
        public static final String I_ID               = "id";
        public static final String I_ADDRESS          = "address";
        public static final String I_NAME             = "name";
        public static final String I_POST_CODE        = "postCode";
        public static final String I_TOWN             = "town";
        public static final String I_COUNTRY          = "country";
        public static final String I_COMPANY_ID       = "companyId";
        public static final String I_ITEMS_TO_INVOICE = "itemsToInvoice";

    }

    public static final String C_MAIN_STACK = "mainStack";

    public static class C_MAIN_STACK_PAGES
    {
        public static final String MAIN   = "main";
        public static final String EDIT   = "edit";
        public static final String INSERT = "insert";

    }

    public static final String C_CUSTOMER_CONTACTS_TOOLBAR = "CustomerContactsToolbar";
    public static final String C_CUSTOMER_CONTACTS         = "CustomerContacts";
    public static final String C_CUSTOMER_CONTACTS_EDIT    = "CustomerContactsEdit";
    public static final String C_CUSTOMER_CONTACTS_INSERT  = "CustomerContactsInsert";

    public static final String AC_ADD_NEW_CONTACT          = "ADD_NEW_CONTACT";
    public static final String AC_DELETE_CUSTOMER_CONTACT  = "DELETE_CUSTOMER_CONTACT";
    public static final String AC_EDIT_CANCEL              = "EDIT_CANCEL";
    public static final String AC_EDIT_CONTACT             = "EDIT_CONTACT";
    public static final String AC_EDIT_SAVE                = "EDIT_SAVE";
    public static final String AC_INSERT_CANCEL            = "INSERT_CANCEL";
    public static final String AC_INSERT_SAVE              = "INSERT_SAVE";
    public static final String AC_QUERY_CONTACTS           = "QUERY_CONTACTS";

    public static final String P_IN_EDIT_MODE              = "IN_EDIT_MODE";

}