package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_INVOICE_OVERVIEW {
	public static final String ID = "InvoiceOverview";

	public static class B_OPEN_INVOICES {
		public static final String ID = "OpenInvoices";
		public static final String I_NR = "nr";
		public static final String I_PAYINF_ID = "payinfId";
		public static final String I_PAID = "paid";
		public static final String I_USER_ID = "userId";
		public static final String I_AMOUNT_EXCL_VAT = "amountExclVat";
		public static final String I_INV_DATE = "invDate";
		public static final String I_CONF_ID = "confId";
		public static final String I_PRINTED = "printed";
		public static final String I_ID = "id";
		public static final String I_INVOICE_ID = "invoiceId";
		public static final String I_SUBJECT = "subject";
		public static final String I_CUST_ID = "custId";
		public static final String I_STATUS = "status";
		public static final String I_AMOUNT_INCL_VAT = "amountInclVat";

	}

	public static final String C_OPEN_INVOICES = "OpenInvoices";

}