package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_INVOICE_OVERVIEW
{
    public static final String ID = "InvoiceOverview";

    public static class B_INVOICE_CUSTOMERS_CTRL
    {
        public static final String ID                = "InvoiceCustomersCtrl";
        public static final String I_CUSTOMER_CHOICE = "CustomerChoice";

    }

    public static class B_INVOICE_CUSTOMERS
    {
        public static final String ID                = "InvoiceCustomers";
        public static final String I_CUSTOMER_CHOICE = "CustomerChoice";
        public static final String I_INDICATOR       = "indicator";
        public static final String I_ADDRESS         = "address";
        public static final String I_TOWN            = "town";
        public static final String I_POST_CODE       = "postCode";
        public static final String I_NAME            = "name";
        public static final String I_COUNTRY         = "country";
        public static final String I_ID              = "id";
        public static final String I_USER_ID         = "userId";

    }

    public static class B_PROJECT_TIME
    {
        public static final String ID                = "ProjectTime";
        public static final String I_HEADER_ROW      = "headerRow";
        public static final String I_DESCRIPTION     = "description";
        public static final String I_PROJECT_STATUS  = "projectStatus";
        public static final String I_PROJECT_USER_ID = "projectUserId";
        public static final String I_CUSTOMER_ID     = "customerId";
        public static final String I_TASK_ID         = "taskId";
        public static final String I_TASK_NAME       = "taskName";
        public static final String I_TASK_VAT_ID     = "taskVatId";
        public static final String I_VAT_RATE        = "vatRate";
        public static final String I_VAT_NAME        = "vatName";
        public static final String I_TASK_PAY_RATE   = "taskPayRate";
        public static final String I_WORK_HOURS      = "workHours";
        public static final String I_TOTAL_EXCL_VAT  = "totalExclVat";
        public static final String I_TOTAL_INCL_VAT  = "totalInclVat";

    }

    public static class B_CHOSEN_CUSTOMER
    {
        public static final String ID                     = "ChosenCustomer";
        public static final String I_CUSTOMER_INFORMATION = "customerInformation";
        public static final String I_CREATE_INVOICE       = "createInvoice";

    }

    public static class B_WORKING_HOURS
    {
        public static final String ID                 = "WorkingHours";
        public static final String I_HEADER_ROW       = "headerRow";
        public static final String I_DESCRIPTION      = "description";
        public static final String I_PROJECT_STATUS   = "projectStatus";
        public static final String I_PROJECT_USER_ID  = "projectUserId";
        public static final String I_CUSTOMER_ID      = "customerId";
        public static final String I_TASK_ID          = "taskId";
        public static final String I_TASK_NAME        = "taskName";
        public static final String I_TASK_VAT_ID      = "taskVatId";
        public static final String I_VAT_RATE         = "vatRate";
        public static final String I_VAT_NAME         = "vatName";
        public static final String I_TASK_PAY_RATE    = "taskPayRate";
        public static final String I_WORK_HOURS       = "workHours";
        public static final String I_TOTAL_EXCL_VAT   = "totalExclVat";
        public static final String I_TOTAL_INCL_VAT   = "totalInclVat";
        public static final String I_WORK_DATE        = "workDate";
        public static final String I_START_TIME       = "startTime";
        public static final String I_END_TIME         = "endTime";
        public static final String I_WORK_DESCRIPTION = "workDescription";

    }

    public static class B_INVOICE_PROJECT_TIME
    {
        public static final String ID                    = "InvoiceProjectTime";
        public static final String I_REMOVE_FROM_INVOICE = "removeFromInvoice";
        public static final String I_HEADER_ROW          = "headerRow";
        public static final String I_DESCRIPTION         = "description";
        public static final String I_PROJECT_STATUS      = "projectStatus";
        public static final String I_PROJECT_USER_ID     = "projectUserId";
        public static final String I_CUSTOMER_ID         = "customerId";
        public static final String I_TASK_ID             = "taskId";
        public static final String I_TASK_NAME           = "taskName";
        public static final String I_TASK_VAT_ID         = "taskVatId";
        public static final String I_VAT_RATE            = "vatRate";
        public static final String I_VAT_NAME            = "vatName";
        public static final String I_TASK_PAY_RATE       = "taskPayRate";
        public static final String I_WORK_HOURS          = "workHours";
        public static final String I_TOTAL_EXCL_VAT      = "totalExclVat";
        public static final String I_TOTAL_INCL_VAT      = "totalInclVat";

    }

    public static final String C_INVOICE_OVERVIEW_SPLIT = "invoiceOverviewSplit";
    public static final String C_CUSTOMERS              = "Customers";
    public static final String C_INVOICE_CUSTOMERS_CTRL = "InvoiceCustomersCtrl";
    public static final String C_OPEN_INV_CUST          = "OpenInvCust";
    public static final String C_OVERVIEW               = "overview";
    public static final String C_CUSTOMER_HEADER        = "CustomerHeader";
    public static final String C_INVOICE_TAB            = "InvoiceTab";

    public static class C_INVOICE_TAB_PAGES
    {
        public static final String NON_INVOICED_HOURS = "NonInvoicedHours";
        public static final String WORK_HOURS         = "WorkHours";

    }

    public static final String C_PROJECT_TIME            = "ProjectTime";
    public static final String C_WORKING_HOURS           = "WorkingHours";
    public static final String C_INVOICE_CREATION_POPUP  = "InvoiceCreationPopup";
    public static final String C_INVOICE_PROJECT_TIME    = "InvoiceProjectTime";

    public static final String AC_CREATE_INVOICE         = "CREATE_INVOICE";
    public static final String AC_REMOVE_FROM_INVOICE    = "REMOVE_FROM_INVOICE";
    public static final String AC_REQUERY_CUSTOMERS      = "REQUERY_CUSTOMERS";
    public static final String AC_REQUERY_OPEN_POSITIONS = "REQUERY_OPEN_POSITIONS";

}