package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_INVOICE_OLD
{
    public static final String ID = "Invoice_old";

    public static class B_INVOICE_TOOL_BAR
    {
        public static final String ID       = "InvoiceToolBar";
        public static final String I_HOME   = "home";
        public static final String I_NEW    = "new";
        public static final String I_EDIT   = "edit";
        public static final String I_DELETE = "delete";

    }

    public static class B_INVOICE
    {
        public static final String ID                = "Invoice";
        public static final String I_NR              = "nr";
        public static final String I_AMOUNT_EXCL_VAT = "amountExclVat";
        public static final String I_AMOUNT_INCL_VAT = "amountInclVat";
        public static final String I_ID              = "id";
        public static final String I_INV_DATE        = "invDate";
        public static final String I_USER_ID         = "userId";
        public static final String I_CONF_ID         = "confId";
        public static final String I_PAYINF_ID       = "payinfId";
        public static final String I_PRINTED         = "printed";
        public static final String I_INVOICE_ID      = "invoiceId";
        public static final String I_CUST_ID         = "custId";
        public static final String I_PAID            = "paid";

    }

    public static class B_INVOICE_INFO
    {
        public static final String ID                = "InvoiceInfo";
        public static final String I_NR              = "nr";
        public static final String I_AMOUNT_EXCL_VAT = "amountExclVat";
        public static final String I_AMOUNT_INCL_VAT = "amountInclVat";
        public static final String I_ID              = "id";
        public static final String I_INV_DATE        = "invDate";
        public static final String I_USER_ID         = "userId";
        public static final String I_CONF_ID         = "confId";
        public static final String I_PAYINF_ID       = "payinfId";
        public static final String I_PRINTED         = "printed";
        public static final String I_INVOICE_ID      = "invoiceId";
        public static final String I_CUST_ID         = "custId";
        public static final String I_PAID            = "paid";

    }

    public static class B_INVOICE_POSITIONS
    {
        public static final String ID                   = "InvoicePositions";
        public static final String I_HOURS_WORKED       = "hoursWorked";
        public static final String I_USER_ID            = "userId";
        public static final String I_POSITION           = "position";
        public static final String I_DESCRIPTION        = "description";
        public static final String I_CUPR_ID            = "cuprId";
        public static final String I_ID                 = "id";
        public static final String I_INV_ID             = "invId";
        public static final String I_VAT_ID             = "vatId";
        public static final String I_AMOUNT             = "amount";
        public static final String I_VAT_RATE           = "vatRate";
        public static final String I_CUST_PROJ_PAY_RATE = "custProjPayRate";

    }

    public static class B_INVOICE_POSITION_TOOL_BAR
    {
        public static final String ID       = "InvoicePositionToolBar";
        public static final String I_HOME   = "home";
        public static final String I_NEW    = "new";
        public static final String I_EDIT   = "edit";
        public static final String I_DELETE = "delete";
        public static final String I_HEADER = "header";

    }

    public static class L_COMPANY_LOV
    {
        public static final String ID                    = "CompanyLov";
        public static final String I_NAME                = "name";
        public static final String I_BANK_TOWN           = "bankTown";
        public static final String I_IBAN                = "iban";
        public static final String I_TOWN                = "town";
        public static final String I_ADDRESS_LINE_1      = "addressLine1";
        public static final String I_BANK_ADDRESS_LINE_3 = "bankAddressLine3";
        public static final String I_BANK_POST_CODE      = "bankPostCode";
        public static final String I_ADDRESS_LINE_3      = "addressLine3";
        public static final String I_BANK_ADDRESS_LINE_1 = "bankAddressLine1";
        public static final String I_ADDRESS_LINE_2      = "addressLine2";
        public static final String I_ID                  = "id";
        public static final String I_BANK_ADDRESS_LINE_2 = "bankAddressLine2";
        public static final String I_BANK_NAME           = "bankName";
        public static final String I_POST_CODE           = "postCode";

    }

    public static class L_PROJECTS_LOV
    {
        public static final String ID            = "ProjectsLov";
        public static final String I_NAME        = "name";
        public static final String I_ID          = "id";
        public static final String I_CUST_ID     = "custId";
        public static final String I_DESCRIPTION = "description";

    }

    public static class L_PAYMENT_INFO_LOV
    {
        public static final String ID              = "PaymentInfoLov";
        public static final String I_ID            = "id";
        public static final String I_PAYMENT_TERMS = "paymentTerms";

    }

    public static class L_CUSTOMER_LOV
    {
        public static final String ID               = "CustomerLov";
        public static final String I_ID             = "id";
        public static final String I_ADDRESS_LINE_1 = "addressLine1";
        public static final String I_ADDRESS_LINE_2 = "addressLine2";
        public static final String I_NAME           = "name";
        public static final String I_POST_CODE      = "postCode";
        public static final String I_ADDRESS_LINE_3 = "addressLine3";
        public static final String I_TOWN           = "town";
        public static final String I_COUNTRY        = "country";

    }

    public static class L_VAT_LOV
    {
        public static final String ID      = "VatLov";
        public static final String I_NOTES = "notes";
        public static final String I_RATE  = "rate";
        public static final String I_NAME  = "name";
        public static final String I_ID    = "id";

    }

    public static final String C_INVOICE_TOOL_BAR          = "InvoiceToolBar";
    public static final String C_INVOICE                   = "Invoice";
    public static final String C_INVOICE_INFO              = "InvoiceInfo";
    public static final String C_INVOICE_POSITIONS_GRP     = "InvoicePositionsGRP";
    public static final String C_INVOICE_POSITION_TOOL_BAR = "InvoicePositionToolBar";
    public static final String C_INVOICE_POSITIONS         = "InvoicePositions";

    public static final String AC_DELETE_POSITION          = "DELETE_POSITION";
    public static final String AC_EDIT_POSITION            = "EDIT_POSITION";
    public static final String AC_NEW_POSITION             = "NEW_POSITION";
    public static final String AC_TOOLBAR_DELETE           = "TOOLBAR_DELETE";
    public static final String AC_TOOLBAR_EDIT             = "TOOLBAR_EDIT";
    public static final String AC_TOOLBAR_HOME             = "TOOLBAR_HOME";
    public static final String AC_TOOLBAR_NEW              = "TOOLBAR_NEW";

}