package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_LAUNCH_PAGE
{
    public static final String ID = "LaunchPage";

    public static class B_LAUNCHER
    {
        public static final String ID           = "Launcher";
        public static final String I_INVOICES   = "invoices";
        public static final String I_MASTERDATA = "masterdata";
        public static final String I_CUSTOMERS  = "customers";
        public static final String I_COMPANY    = "company";
        public static final String I_PROJECTS   = "projects";

    }

    public static final String C_LAUNCHER               = "Launcher";

    public static final String AC_OPEN_COMPANIES        = "OPEN_COMPANIES";
    public static final String AC_OPEN_CUSTOMERS        = "OPEN_CUSTOMERS";
    public static final String AC_OPEN_INVOICE_OVERVIEW = "OPEN_INVOICE_OVERVIEW";
    public static final String AC_OPEN_MASTER_DATA      = "OPEN_MASTER_DATA";
    public static final String AC_OPEN_PROJECTS         = "OPEN_PROJECTS";

}