package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_MASTER_DATA_CONTACT_TYPES
{
    public static final String ID = "MasterDataContactTypes";

    public static class B_CONTACT_TYPES_TOOLBAR
    {
        public static final String ID                     = "ContactTypesToolbar";
        public static final String I_ADD_NEW_CONTACT_TYPE = "addNewContactType";

    }

    public static class B_CONTACT_TYPES
    {
        public static final String ID            = "ContactTypes";
        public static final String I_TYPE        = "type";
        public static final String I_ID          = "id";
        public static final String I_DESCRIPTION = "description";
        public static final String I_COMPANY_ID  = "companyId";
        public static final String I_EDIT        = "edit";
        public static final String I_DELETE      = "delete";

    }

    public static final String C_CONTACT_TYPES_TOOLBAR = "ContactTypesToolbar";
    public static final String C_CONTACT_TYPES         = "ContactTypes";

    public static final String AC_CREATE_CONTACT_TYPE  = "CREATE_CONTACT_TYPE";
    public static final String AC_DELETE_CONTACT_TYPE  = "DELETE_CONTACT_TYPE";
    public static final String AC_MODIFY_CONTACT       = "MODIFY_CONTACT";

}