package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_MASTER_DATA_SALUTATION {
	public static final String ID = "MasterDataSalutation";

	public static class B_SALUTATIONS_TOOLBAR {
		public static final String ID = "SalutationsToolbar";
		public static final String I_ADD_NEW_SALUTATION_TYPE = "addNewSalutationType";

	}

	public static class B_SALUTATIONS {
		public static final String ID = "Salutations";
		public static final String I_VALUE = "value";
		public static final String I_ID = "id";
		public static final String I_COMPANY_ID = "companyId";
		public static final String I_DELETE = "delete";
		public static final String I_EDIT = "edit";

	}

	public static final String C_SALUTATION_TOOLBAR = "SalutationToolbar";
	public static final String C_SALUTATIONS = "Salutations";

	public static final String AC_CREATE_SALUTATION = "CREATE_SALUTATION";
	public static final String AC_DELETE_SALUTATION = "DELETE_SALUTATION";
	public static final String AC_MODIFY_SALUTATION = "MODIFY_SALUTATION";

}