package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_PROJECTS
{
    public static final String ID = "Projects";

    public static class B_PROJECTS_TOOLBAR
    {
        public static final String ID                   = "ProjectsToolbar";
        public static final String I_CREATE_NEW_PROJECT = "createNewProject";
        public static final String I_CUSTOMER_ID        = "customerId";
        public static final String I_REFRESH            = "refresh";
        public static final String I_STATUS             = "status";

    }

    public static class B_PROJECTS
    {
        public static final String ID                               = "Projects";
        public static final String I_ID                             = "id";
        public static final String I_DESCRIPTION                    = "description";
        public static final String I_NAME                           = "name";
        public static final String I_STATUS                         = "status";
        public static final String I_STATUS_NAME                    = "statusName";
        public static final String I_COMPANY_ID                     = "companyId";
        public static final String I_CUSTOMER_ID                    = "customerId";
        public static final String I_START_DATE                     = "startDate";
        public static final String I_END_DATE                       = "endDate";
        public static final String I_NOTES                          = "notes";
        public static final String I_TASK_CPR_ID                    = "taskCprId";
        public static final String I_TASK_NOTES                     = "taskNotes";
        public static final String I_TASK_NAME                      = "taskName";
        public static final String I_TASK_PAY_RATE                  = "taskPayRate";
        public static final String I_TASK_USER_ID                   = "taskUserId";
        public static final String I_TASK_FIX_PRICE                 = "taskFixPrice";
        public static final String I_TASK_STATUS                    = "taskStatus";
        public static final String I_TASK_INVOICEABLE               = "taskInvoiceable";
        public static final String I_INVOICEABLE                    = "invoiceable";
        public static final String I_INVOICEABLE_IMAGE              = "invoiceableImage";
        public static final String I_FIX_PRICE                      = "fixPrice";
        public static final String I_CUSTOMER_NAME                  = "customerName";
        public static final String I_CUSTOMER_ADDRESS               = "customerAddress";
        public static final String I_CUSTOMER_POST_CODE             = "customerPostCode";
        public static final String I_CUSTOMER_TOWN                  = "customerTown";
        public static final String I_CUSTOMER_COUNTRY               = "customerCountry";
        public static final String I_PROJECT_PROCESS_DESCRIPTION    = "projectProcessDescription";
        public static final String I_BACK                           = "back";
        public static final String I_MODIFY                         = "modify";
        public static final String I_ADD_NEW_TASK                   = "addNewTask";
        public static final String I_OPEN_ITEMS_IMAGE               = "openItemsImage";
        public static final String I_PLANNED_ITEMS_IMAGE            = "plannedItemsImage";
        public static final String I_APPROVED_ITEMS_IMAGE           = "approvedItemsImage";
        public static final String I_MARKED_FOR_INVOICE_ITEMS_IMAGE = "markedForInvoiceItemsImage";
        public static final String I_OPEN_ITEMS                     = "openItems";
        public static final String I_PLANNED_ITEMS                  = "plannedItems";
        public static final String I_APPROVED_ITEMS                 = "approvedItems";
        public static final String I_MARKED_FOR_INVOICE_ITEMS       = "markedForInvoiceItems";
        public static final String I_EDIT                           = "edit";
        public static final String I_TASKS                          = "tasks";
        public static final String I_DISPLAY_TEXT                   = "displayText";

    }

    public static class B_PROJECT_KEY
    {
        public static final String ID                         = "projectKey";
        public static final String I_TASK_ICON                = "taskIcon";
        public static final String I_TASK_ICON_LABEL          = "taskIconLabel";
        public static final String I_TIME_ICON                = "timeIcon";
        public static final String I_TIME_ICON_LABEL          = "timeIconLabel";
        public static final String I_PLANNED_HOURS            = "plannedHours";
        public static final String I_PLANNED_HOURS_LABEL      = "plannedHoursLabel";
        public static final String I_APPROVED_HOURS           = "approvedHours";
        public static final String I_APPROVED_HOURS_LABEL     = "approvedHoursLabel";
        public static final String I_MARKED_FOR_INVOICE       = "markedForInvoice";
        public static final String I_MARKED_FOR_INVOICE_LABEL = "markedForInvoiceLabel";
        public static final String I_INVOICEABLE              = "invoiceable";
        public static final String I_INVOICEABLE_LABEL        = "invoiceableLabel";

    }

    public static class B_PROJECTS_EDIT
    {
        public static final String ID                  = "ProjectsEdit";
        public static final String I_NAME              = "name";
        public static final String I_NAME_ERROR        = "nameError";
        public static final String I_DESCRIPTION       = "description";
        public static final String I_STATUS            = "status";
        public static final String I_STATUS_VALUE      = "statusValue";
        public static final String I_STATUS_ERROR      = "statusError";
        public static final String I_INVOICEABLE       = "invoiceable";
        public static final String I_FIX_PRICE         = "fixPrice";
        public static final String I_START_DATE        = "startDate";
        public static final String I_END_DATE          = "endDate";
        public static final String I_NOTES             = "notes";
        public static final String I_CUSTOMER_ID       = "customerId";
        public static final String I_CUSTOMER_ID_ERROR = "customerIdError";
        public static final String I_CUSTOMER_NAME     = "customerName";
        public static final String I_SAVE              = "save";
        public static final String I_CANCEL            = "cancel";
        public static final String I_PAGE_TITLE        = "pageTitle";

    }

    public static class B_PROJECT_INSERT
    {
        public static final String ID                  = "ProjectInsert";
        public static final String I_NAME              = "name";
        public static final String I_NAME_ERROR        = "nameError";
        public static final String I_DESCRIPTION       = "description";
        public static final String I_STATUS            = "status";
        public static final String I_STATUS_VALUE      = "statusValue";
        public static final String I_STATUS_ERROR      = "statusError";
        public static final String I_INVOICEABLE       = "invoiceable";
        public static final String I_FIX_PRICE         = "fixPrice";
        public static final String I_START_DATE        = "startDate";
        public static final String I_END_DATE          = "endDate";
        public static final String I_NOTES             = "notes";
        public static final String I_CUSTOMER_ID       = "customerId";
        public static final String I_CUSTOMER_ID_ERROR = "customerIdError";
        public static final String I_CUSTOMER_NAME     = "customerName";
        public static final String I_SAVE              = "save";
        public static final String I_CANCEL            = "cancel";
        public static final String I_PAGE_TITLE        = "pageTitle";
        public static final String I_TASK_TITLE        = "taskTitle";
        public static final String I_TASK_NAME         = "taskName";
        public static final String I_TASK_NAME_ERROR   = "taskNameError";
        public static final String I_TASK_INVOICEABLE  = "taskInvoiceable";
        public static final String I_TASK_STATUS       = "taskStatus";
        public static final String I_TASK_STATUS_ERROR = "taskStatusError";
        public static final String I_TASK_FIX_PRICE    = "taskFixPrice";
        public static final String I_TASK_HOURLY_RATE  = "taskHourlyRate";
        public static final String I_TASK_NOTES        = "taskNotes";

    }

    public static class L_VAT_RATE
    {
        public static final String ID           = "VatRate";
        public static final String I_NOTES      = "notes";
        public static final String I_RATE       = "rate";
        public static final String I_NAME       = "name";
        public static final String I_ID         = "id";
        public static final String I_COMPANY_ID = "companyId";

    }

    public static class L_CUSTOMER
    {
        public static final String ID                 = "Customer";
        public static final String I_ID               = "id";
        public static final String I_ADDRESS          = "address";
        public static final String I_NAME             = "name";
        public static final String I_POST_CODE        = "postCode";
        public static final String I_TOWN             = "town";
        public static final String I_COUNTRY          = "country";
        public static final String I_COMPANY_ID       = "companyId";
        public static final String I_ITEMS_TO_INVOICE = "itemsToInvoice";

    }

    public static class L_SALUTATIONS
    {
        public static final String ID           = "Salutations";
        public static final String I_VALUE      = "value";
        public static final String I_ID         = "id";
        public static final String I_COMPANY_ID = "companyId";

    }

    public static class L_PROJECT_STATUS
    {
        public static final String ID            = "ProjectStatus";
        public static final String I_DESCRIPTION = "description";
        public static final String I_NAME        = "name";
        public static final String I_CODE        = "code";

    }

    public static class L_TASK_STATUS
    {
        public static final String ID            = "TaskStatus";
        public static final String I_DESCRIPTION = "description";
        public static final String I_NAME        = "name";
        public static final String I_CODE        = "code";

    }

    public static class L_PROJECTS
    {
        public static final String ID            = "Projects";
        public static final String I_NAME        = "name";
        public static final String I_ID          = "id";
        public static final String I_CUST_ID     = "custId";
        public static final String I_DESCRIPTION = "description";
        public static final String I_COMPANY_ID  = "companyId";
        public static final String I_STATUS      = "status";
        public static final String I_FIX_PRICE   = "fixPrice";

    }

    public static final String C_MAIN_STACK = "mainStack";

    public static class C_MAIN_STACK_PAGES
    {
        public static final String MAIN   = "main";
        public static final String EDIT   = "edit";
        public static final String INSERT = "insert";

    }

    public static final String C_PROJECTS_TOOLBAR      = "ProjectsToolbar";
    public static final String C_PROJECTS              = "Projects";
    public static final String C_PROJECT_KEY           = "projectKey";
    public static final String C_PROJECTS_EDIT         = "ProjectsEdit";
    public static final String C_PROJECTS_INSERT       = "ProjectsInsert";

    public static final String AC_CREATE_NEW_PROJECT   = "CREATE_NEW_PROJECT";
    public static final String AC_EDIT_CANCEL          = "EDIT_CANCEL";
    public static final String AC_EDIT_SAVE            = "EDIT_SAVE";
    public static final String AC_INSERT_CANCEL        = "INSERT_CANCEL";
    public static final String AC_INSERT_SAVE          = "INSERT_SAVE";
    public static final String AC_INVOICEABLE          = "INVOICEABLE";
    public static final String AC_MODIFY_PROJECT       = "MODIFY_PROJECT";
    public static final String AC_REFRESH_PROJECT_LIST = "REFRESH_PROJECT_LIST";
    public static final String AC_SHOW_PROJECT_TASKS   = "SHOW_PROJECT_TASKS";

    public static final String P_IN_EDIT_MODE          = "IN_EDIT_MODE";

}