package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_PROJECTS
{
    public static final String ID = "Projects";

    public static class B_PROJECTS_TOOLBAR
    {
        public static final String ID                   = "ProjectsToolbar";
        public static final String I_CREATE_NEW_PROJECT = "createNewProject";
        public static final String I_CUSTOMER_ID        = "customerId";
        public static final String I_CUSTOMER_NAME      = "customerName";
        public static final String I_REFRESH            = "refresh";
        public static final String I_STATUS_ON_HOLD     = "statusOnHold";
        public static final String I_STATUS_IN_WORK     = "statusInWork";
        public static final String I_STATUS_NEW         = "statusNew";
        public static final String I_STATUS_COMPLETED   = "statusCompleted";
        public static final String I_STATUS_DELETED     = "statusDeleted";

    }

    public static class B_PROJECTS
    {
        public static final String ID                               = "Projects";
        public static final String I_ID                             = "id";
        public static final String I_DESCRIPTION                    = "description";
        public static final String I_NAME                           = "name";
        public static final String I_STATUS                         = "status";
        public static final String I_STATUS_NAME                    = "statusName";
        public static final String I_COMPANY_ID                     = "companyId";
        public static final String I_CUSTOMER_ID                    = "customerId";
        public static final String I_START_DATE                     = "startDate";
        public static final String I_END_DATE                       = "endDate";
        public static final String I_NOTES                          = "notes";
        public static final String I_TASK_CPR_ID                    = "taskCprId";
        public static final String I_TASK_NOTES                     = "taskNotes";
        public static final String I_TASK_NAME                      = "taskName";
        public static final String I_TASK_PAY_RATE                  = "taskPayRate";
        public static final String I_TASK_USER_ID                   = "taskUserId";
        public static final String I_TASK_FIX_PRICE                 = "taskFixPrice";
        public static final String I_TASK_STATUS                    = "taskStatus";
        public static final String I_TASK_INVOICEABLE               = "taskInvoiceable";
        public static final String I_INVOICEABLE                    = "invoiceable";
        public static final String I_INVOICEABLE_IMAGE              = "invoiceableImage";
        public static final String I_FIX_PRICE                      = "fixPrice";
        public static final String I_CUSTOMER_NAME                  = "customerName";
        public static final String I_CUSTOMER_ADDRESS               = "customerAddress";
        public static final String I_CUSTOMER_POST_CODE             = "customerPostCode";
        public static final String I_CUSTOMER_TOWN                  = "customerTown";
        public static final String I_CUSTOMER_COUNTRY               = "customerCountry";
        public static final String I_PROJECT_PROCESS_DESCRIPTION    = "projectProcessDescription";
        public static final String I_BACK                           = "back";
        public static final String I_MODIFY                         = "modify";
        public static final String I_ADD_NEW_TASK                   = "addNewTask";
        public static final String I_OPEN_ITEMS_IMAGE               = "openItemsImage";
        public static final String I_PLANNED_ITEMS_IMAGE            = "plannedItemsImage";
        public static final String I_APPROVED_ITEMS_IMAGE           = "approvedItemsImage";
        public static final String I_MARKED_FOR_INVOICE_ITEMS_IMAGE = "markedForInvoiceItemsImage";
        public static final String I_OPEN_ITEMS                     = "openItems";
        public static final String I_PLANNED_ITEMS                  = "plannedItems";
        public static final String I_APPROVED_ITEMS                 = "approvedItems";
        public static final String I_MARKED_FOR_INVOICE_ITEMS       = "markedForInvoiceItems";
        public static final String I_EDIT                           = "edit";
        public static final String I_TASKS                          = "tasks";

    }

    public static class B_PROJECT_KEY
    {
        public static final String ID                         = "projectKey";
        public static final String I_TASK_ICON                = "taskIcon";
        public static final String I_TASK_ICON_LABEL          = "taskIconLabel";
        public static final String I_TIME_ICON                = "timeIcon";
        public static final String I_TIME_ICON_LABEL          = "timeIconLabel";
        public static final String I_PLANNED_HOURS            = "plannedHours";
        public static final String I_PLANNED_HOURS_LABEL      = "plannedHoursLabel";
        public static final String I_APPROVED_HOURS           = "approvedHours";
        public static final String I_APPROVED_HOURS_LABEL     = "approvedHoursLabel";
        public static final String I_MARKED_FOR_INVOICE       = "markedForInvoice";
        public static final String I_MARKED_FOR_INVOICE_LABEL = "markedForInvoiceLabel";
        public static final String I_INVOICEABLE              = "invoiceable";
        public static final String I_INVOICEABLE_LABEL        = "invoiceableLabel";

    }

    public static class B_PROJECT_TASKS_TOOLBAR
    {
        public static final String ID                    = "ProjectTasksToolbar";
        public static final String I_ADD_NEW             = "addNew";
        public static final String I_PROJECT_INFORMATION = "projectInformation";
        public static final String I_BACK_TO_PROJECTS    = "backToProjects";

    }

    public static class B_PROJECT_TASKS
    {
        public static final String ID                  = "ProjectTasks";
        public static final String I_ID                = "id";
        public static final String I_CPR_ID            = "cprId";
        public static final String I_NOTES             = "notes";
        public static final String I_NAME              = "name";
        public static final String I_PAY_RATE          = "payRate";
        public static final String I_INVOICEABLE       = "invoiceable";
        public static final String I_INVOICEABLE_IMAGE = "invoiceableImage";
        public static final String I_FIX_PRICE         = "fixPrice";
        public static final String I_COMPANY_ID        = "companyId";
        public static final String I_STATUS            = "status";
        public static final String I_MESSAGE_LABEL     = "messageLabel";
        public static final String I_DELETE            = "delete";
        public static final String I_EDIT              = "edit";
        public static final String I_STATUS_NAME       = "statusName";

    }

    public static class B_OPEN_PROJECT_ITEMS
    {
        public static final String ID                        = "OpenProjectItems";
        public static final String I_PROJECT_ID              = "projectId";
        public static final String I_TASK_ID                 = "taskId";
        public static final String I_PROJECT_NAME            = "projectName";
        public static final String I_TASK_NAME               = "taskName";
        public static final String I_TE_MONTH                = "teMonth";
        public static final String I_TE_YEAR                 = "teYear";
        public static final String I_TE_LAST_DAY             = "teLastDay";
        public static final String I_TE_FIRST_DAY            = "teFirstDay";
        public static final String I_WORK_HOURS              = "workHours";
        public static final String I_CREATE_INVOICE_POSITION = "createInvoicePosition";
        public static final String I_PAY_RATE                = "payRate";
        public static final String I_COMPANY_ID              = "companyId";

    }

    public static class B_OPEN_PROJECT_ITEMS_CONTROL
    {
        public static final String ID            = "OpenProjectItemsControl";
        public static final String I_DESCRIPTION = "description";

    }

    public static class B_NEW_INVOICE_ITEM
    {
        public static final String ID             = "NewInvoiceItem";
        public static final String I_DELETE       = "delete";
        public static final String I_PERIOD_LABEL = "periodLabel";
        public static final String I_PERIOD_FROM  = "periodFrom";
        public static final String I_PERIOD_TO    = "periodTo";
        public static final String I_STATUS_LABEL = "statusLabel";
        public static final String I_STATUS       = "status";
        public static final String I_TEXT         = "text";

    }

    public static class B_PLANNED_PROJECT_ITEMS
    {
        public static final String ID                        = "PlannedProjectItems";
        public static final String I_INVP_ID                 = "invpId";
        public static final String I_PROJECT_ID              = "projectId";
        public static final String I_TASK_ID                 = "taskId";
        public static final String I_PROJECT_NAME            = "projectName";
        public static final String I_TASK_NAME               = "taskName";
        public static final String I_TE_MONTH                = "teMonth";
        public static final String I_TE_YEAR                 = "teYear";
        public static final String I_PERIOD_TO               = "periodTo";
        public static final String I_PERIOD_FROM             = "periodFrom";
        public static final String I_WORK_HOURS              = "workHours";
        public static final String I_CREATE_INVOICE_POSITION = "createInvoicePosition";
        public static final String I_DELETE                  = "delete";
        public static final String I_INVP_TEXT               = "invpText";
        public static final String I_EDIT                    = "edit";
        public static final String I_PAY_RATE                = "payRate";
        public static final String I_COMPANY_ID              = "companyId";

    }

    public static class B_APPROVED_PROJECT_ITEMS
    {
        public static final String ID               = "ApprovedProjectItems";
        public static final String I_HOURS_WORKED   = "hoursWorked";
        public static final String I_TASK_NAME      = "taskName";
        public static final String I_STATUS         = "status";
        public static final String I_CUPR_ID        = "cuprId";
        public static final String I_PERIOD_FROM    = "periodFrom";
        public static final String I_INV_ID         = "invId";
        public static final String I_AMOUNT         = "amount";
        public static final String I_ID             = "id";
        public static final String I_PAY_RATE       = "payRate";
        public static final String I_PROJECT_NAME   = "projectName";
        public static final String I_PERIOD_TO      = "periodTo";
        public static final String I_CUPT_ID        = "cuptId";
        public static final String I_FIX_PRICE      = "fixPrice";
        public static final String I_TEXT           = "text";
        public static final String I_DELETE         = "delete";
        public static final String I_ADD_TO_INVOICE = "addToInvoice";
        public static final String I_COMPANY_ID     = "companyId";

    }

    public static class B_MARKED_FOR_INVOICE_PROJECT_ITEMS
    {
        public static final String ID             = "MarkedForInvoiceProjectItems";
        public static final String I_HOURS_WORKED = "hoursWorked";
        public static final String I_TASK_NAME    = "taskName";
        public static final String I_STATUS       = "status";
        public static final String I_CUPR_ID      = "cuprId";
        public static final String I_PERIOD_FROM  = "periodFrom";
        public static final String I_INV_ID       = "invId";
        public static final String I_AMOUNT       = "amount";
        public static final String I_ID           = "id";
        public static final String I_PAY_RATE     = "payRate";
        public static final String I_COMPANY_ID   = "companyId";
        public static final String I_PROJECT_NAME = "projectName";
        public static final String I_PERIOD_TO    = "periodTo";
        public static final String I_CUPT_ID      = "cuptId";
        public static final String I_FIX_PRICE    = "fixPrice";
        public static final String I_TEXT         = "text";
        public static final String I_DELETE       = "delete";

    }

    public static class B_INVOICE_HEADER
    {
        public static final String ID                    = "InvoiceHeader";
        public static final String I_BACK_TO_PROJECTS    = "backToProjects";
        public static final String I_PROJECT_INFORMATION = "projectInformation";

    }

    public static class B_INVOICE_TOTAL
    {
        public static final String ID               = "InvoiceTotal";
        public static final String I_SUBTOTAL_LABEL = "subtotalLabel";
        public static final String I_TAX_LABEL      = "taxLabel";
        public static final String I_TOTAL_LABEL    = "totalLabel";
        public static final String I_SUBTOTAL       = "subtotal";
        public static final String I_TAX            = "tax";
        public static final String I_TOTAL          = "total";
        public static final String I_CREATE_INVOICE = "createInvoice";
        public static final String I_AMOUNT_EXCL    = "amountExcl";
        public static final String I_VAT_AMOUNT     = "vatAmount";
        public static final String I_AMOUNT_INCL    = "amountIncl";

    }

    public static class B_INVOICE_CREATION
    {
        public static final String ID                = "InvoiceCreation";
        public static final String I_ID              = "id";
        public static final String I_COMPANY_ID      = "companyId";
        public static final String I_CUST_ID         = "custId";
        public static final String I_NR_LABEL        = "nrLabel";
        public static final String I_NR              = "nr";
        public static final String I_INV_DATE_LABEL  = "invDateLabel";
        public static final String I_INV_DATE        = "invDate";
        public static final String I_DUE_DATE        = "dueDate";
        public static final String I_DUE_DATE_LABEL  = "dueDateLabel";
        public static final String I_DUE_DATE_INFO   = "dueDateInfo";
        public static final String I_AMOUNT_EXCL_VAT = "amountExclVat";
        public static final String I_VAT_AMOUNT      = "vatAmount";
        public static final String I_AMOUNT_INCL_VAT = "amountInclVat";
        public static final String I_INVOICE_ADDRESS = "invoiceAddress";
        public static final String I_VAT_RATE        = "vatRate";
        public static final String I_INVOICE_SUMMARY = "invoiceSummary";
        public static final String I_INVOICE_NOTES   = "invoiceNotes";
        public static final String I_INVOICE_FOOTER  = "invoiceFooter";

    }

    public static class L_VAT_RATE
    {
        public static final String ID           = "VatRate";
        public static final String I_NOTES      = "notes";
        public static final String I_RATE       = "rate";
        public static final String I_NAME       = "name";
        public static final String I_ID         = "id";
        public static final String I_COMPANY_ID = "companyId";

    }

    public static class L_CUSTOMER
    {
        public static final String ID           = "Customer";
        public static final String I_ID         = "id";
        public static final String I_ADDRESS    = "address";
        public static final String I_NAME       = "name";
        public static final String I_POST_CODE  = "postCode";
        public static final String I_TOWN       = "town";
        public static final String I_COUNTRY    = "country";
        public static final String I_COMPANY_ID = "companyId";

    }

    public static class L_SALUTATIONS
    {
        public static final String ID           = "Salutations";
        public static final String I_VALUE      = "value";
        public static final String I_ID         = "id";
        public static final String I_COMPANY_ID = "companyId";

    }

    public static class L_PROJECT_STATUS
    {
        public static final String ID            = "ProjectStatus";
        public static final String I_DESCRIPTION = "description";
        public static final String I_NAME        = "name";
        public static final String I_CODE        = "code";

    }

    public static class L_TASK_STATUS
    {
        public static final String ID            = "TaskStatus";
        public static final String I_DESCRIPTION = "description";
        public static final String I_NAME        = "name";
        public static final String I_CODE        = "code";

    }

    public static final String C_PROJECT_STACK = "projectStack";

    public static class C_PROJECT_STACK_PAGES
    {
        public static final String PROJECTS = "projects";
        public static final String INVOICE  = "invoice";
        public static final String TASKS    = "tasks";

    }

    public static final String C_PROJECTS_TOOLBAR    = "ProjectsToolbar";
    public static final String C_PROJECTS            = "Projects";
    public static final String C_PROJECT_KEY         = "projectKey";
    public static final String C_INVOICE_HEADER      = "InvoiceHeader";
    public static final String C_PROJECT_INVOICE_TAB = "ProjectInvoiceTab";

    public static class C_PROJECT_INVOICE_TAB_PAGES
    {
        public static final String INVOICE_PLANNING = "InvoicePlanning";
        public static final String INVOICE_CREATION = "InvoiceCreation";

    }

    public static final String C_INVOICE_SPLIT                    = "invoiceSplit";
    public static final String C_OPEN_PROJECT_ITEMS               = "OpenProjectItems";
    public static final String C_PLANNED_PROJECT_ITEMS            = "PlannedProjectItems";
    public static final String C_INVOICE_CREATION_SPLIT           = "InvoiceCreationSplit";
    public static final String C_APPROVED_PROJECT_ITEMS           = "ApprovedProjectItems";
    public static final String C_MARKED_FOR_INVOICE               = "markedForInvoice";
    public static final String C_MARKED_FOR_INVOICE_PROJECT_ITEMS = "MarkedForInvoiceProjectItems";
    public static final String C_INVOICE_TOTAL                    = "InvoiceTotal";
    public static final String C_PROJECT_TASKS_TOOLBAR            = "ProjectTasksToolbar";
    public static final String C_PROJECT_TASKS                    = "ProjectTasks";
    public static final String C_NEW_INVOICE_ITEM_POPUP           = "NewInvoiceItemPopup";
    public static final String C_NEW_INVOICE_ITEM                 = "NewInvoiceItem";
    public static final String C_INVOICE_CREATION_POPUP           = "InvoiceCreationPopup";
    public static final String C_INVOICE_CREATION                 = "InvoiceCreation";

    public static final String AC_ADD_NEW_TASK                    = "ADD_NEW_TASK";
    public static final String AC_ADD_TO_INVOICE                  = "ADD_TO_INVOICE";
    public static final String AC_ADD_TO_INV_POS                  = "ADD_TO_INV_POS";
    public static final String AC_APPROVE_INV_POS                 = "APPROVE_INV_POS";
    public static final String AC_BACK_TO_PROJECT_OVERVIEW        = "BACK_TO_PROJECT_OVERVIEW";
    public static final String AC_CREATE_FINAL_INVOICE            = "CREATE_FINAL_INVOICE";
    public static final String AC_CREATE_INVOICE_POSITION         = "CREATE_INVOICE_POSITION";
    public static final String AC_CREATE_NEW_PROJECT              = "CREATE_NEW_PROJECT";
    public static final String AC_DELETE_APPROVED_ITEM            = "DELETE_APPROVED_ITEM";
    public static final String AC_DELETE_MARKED_FOR_INVOICE__ITEM = "DELETE_MARKED_FOR_INVOICE__ITEM";
    public static final String AC_DELETE_PLANNED_ITEM             = "DELETE_PLANNED_ITEM";
    public static final String AC_DELETE_PROJECT_TASK             = "DELETE_PROJECT_TASK";
    public static final String AC_EDIT_PLANNED_ITEM               = "EDIT_PLANNED_ITEM";
    public static final String AC_EDIT_PROJECT_TASK               = "EDIT_PROJECT_TASK";
    public static final String AC_INVOICEABLE                     = "INVOICEABLE";
    public static final String AC_INVOICEABLE_TASK                = "INVOICEABLE_TASK";
    public static final String AC_MODIFY_PROJECT                  = "MODIFY_PROJECT";
    public static final String AC_OPEN_CUSTOMER                   = "OPEN_CUSTOMER";
    public static final String AC_PROJECT_DETAILS                 = "PROJECT_DETAILS";
    public static final String AC_PROJECT_DETAILS_CREATION        = "PROJECT_DETAILS_CREATION";
    public static final String AC_PROJECT_TASKS                   = "PROJECT_TASKS";
    public static final String AC_REFRESH_PROJECT_LIST            = "REFRESH_PROJECT_LIST";

}