package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_PROJECT
{
    public static final String ID = "Project";

    public static class B_PROJECTS
    {
        public static final String ID            = "Projects";
        public static final String I_ID          = "id";
        public static final String I_DESCRIPTION = "description";
        public static final String I_NAME        = "name";
        public static final String I_USER_ID     = "userId";
        public static final String I_CUSTOMER_ID = "customerId";
        public static final String I_END_DATE    = "endDate";
        public static final String I_START_DATE  = "startDate";
        public static final String I_STATUS      = "status";
        public static final String I_NOTES       = "notes";

    }

    public static class B_PROJECT_TOOL_BAR
    {
        public static final String ID           = "ProjectToolBar";
        public static final String I_HOME       = "home";
        public static final String I_NEW        = "new";
        public static final String I_EDIT       = "edit";
        public static final String I_DELETE     = "delete";
        public static final String I_CUSTOMER   = "customer";
        public static final String I_CUSTOMERID = "customerid";

    }

    public static class L_CUSTOMER_LOV
    {
        public static final String ID          = "CustomerLov";
        public static final String I_ID        = "id";
        public static final String I_ADDRESS   = "address";
        public static final String I_NAME      = "name";
        public static final String I_POST_CODE = "postCode";
        public static final String I_TOWN      = "town";
        public static final String I_COUNTRY   = "country";

    }

    public static final String C_PROJECT_TOOL_BAR = "ProjectToolBar";
    public static final String C_PROJECTS         = "Projects";

    public static final String AC_TOOLBAR_DELETE  = "TOOLBAR_DELETE";
    public static final String AC_TOOLBAR_EDIT    = "TOOLBAR_EDIT";
    public static final String AC_TOOLBAR_HOME    = "TOOLBAR_HOME";
    public static final String AC_TOOLBAR_NEW     = "TOOLBAR_NEW";

}