package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_PROJECTS
{
    public static final String ID = "Projects";

    public static class B_PROJECTS_TOOLBAR
    {
        public static final String ID                   = "ProjectsToolbar";
        public static final String I_CREATE_NEW_PROJECT = "createNewProject";

    }

    public static class B_PROJECTS
    {
        public static final String ID                            = "Projects";
        public static final String I_ID                          = "id";
        public static final String I_DESCRIPTION                 = "description";
        public static final String I_NAME                        = "name";
        public static final String I_STATUS                      = "status";
        public static final String I_STATUS_NAME                 = "statusName";
        public static final String I_USER_ID                     = "userId";
        public static final String I_CUSTOMER_ID                 = "customerId";
        public static final String I_START_DATE                  = "startDate";
        public static final String I_END_DATE                    = "endDate";
        public static final String I_NOTES                       = "notes";
        public static final String I_TASK_CPR_ID                 = "taskCprId";
        public static final String I_TASK_NOTES                  = "taskNotes";
        public static final String I_TASK_NAME                   = "taskName";
        public static final String I_TASK_PAY_RATE               = "taskPayRate";
        public static final String I_TASK_USER_ID                = "taskUserId";
        public static final String I_TASK_FIX_PRICE              = "taskFixPrice";
        public static final String I_TASK_STATUS                 = "taskStatus";
        public static final String I_TASK_INVOICEABLE            = "taskInvoiceable";
        public static final String I_INVOICEABLE                 = "invoiceable";
        public static final String I_INVOICEABLE_IMAGE           = "invoiceableImage";
        public static final String I_FIX_PRICE                   = "fixPrice";
        public static final String I_VAT_ID                      = "vatId";
        public static final String I_CCY_ID                      = "ccyId";
        public static final String I_CCY_CODE                    = "ccyCode";
        public static final String I_VAT_NAME                    = "vatName";
        public static final String I_VAT_RATE                    = "vatRate";
        public static final String I_CUSTOMER_NAME               = "customerName";
        public static final String I_CUSTOMER_ADDRESS            = "customerAddress";
        public static final String I_CUSTOMER_POST_CODE          = "customerPostCode";
        public static final String I_CUSTOMER_TOWN               = "customerTown";
        public static final String I_CUSTOMER_COUNTRY            = "customerCountry";
        public static final String I_PROJECT_PROCESS_DESCRIPTION = "projectProcessDescription";
        public static final String I_BACK                        = "back";
        public static final String I_MODIFY                      = "modify";
        public static final String I_ADD_NEW_TASK                = "addNewTask";

    }

    public static class B_PROJECTS_DETAIL
    {
        public static final String ID                            = "ProjectsDetail";
        public static final String I_ID                          = "id";
        public static final String I_DESCRIPTION                 = "description";
        public static final String I_NAME                        = "name";
        public static final String I_STATUS                      = "status";
        public static final String I_STATUS_NAME                 = "statusName";
        public static final String I_USER_ID                     = "userId";
        public static final String I_CUSTOMER_ID                 = "customerId";
        public static final String I_START_DATE                  = "startDate";
        public static final String I_END_DATE                    = "endDate";
        public static final String I_NOTES                       = "notes";
        public static final String I_TASK_CPR_ID                 = "taskCprId";
        public static final String I_TASK_NOTES                  = "taskNotes";
        public static final String I_TASK_NAME                   = "taskName";
        public static final String I_TASK_PAY_RATE               = "taskPayRate";
        public static final String I_TASK_USER_ID                = "taskUserId";
        public static final String I_TASK_FIX_PRICE              = "taskFixPrice";
        public static final String I_TASK_STATUS                 = "taskStatus";
        public static final String I_TASK_INVOICEABLE            = "taskInvoiceable";
        public static final String I_INVOICEABLE                 = "invoiceable";
        public static final String I_INVOICEABLE_IMAGE           = "invoiceableImage";
        public static final String I_FIX_PRICE                   = "fixPrice";
        public static final String I_VAT_ID                      = "vatId";
        public static final String I_CCY_ID                      = "ccyId";
        public static final String I_CCY_CODE                    = "ccyCode";
        public static final String I_VAT_NAME                    = "vatName";
        public static final String I_VAT_RATE                    = "vatRate";
        public static final String I_CUSTOMER_NAME               = "customerName";
        public static final String I_CUSTOMER_ADDRESS            = "customerAddress";
        public static final String I_CUSTOMER_POST_CODE          = "customerPostCode";
        public static final String I_CUSTOMER_TOWN               = "customerTown";
        public static final String I_CUSTOMER_COUNTRY            = "customerCountry";
        public static final String I_PROJECT_PROCESS_DESCRIPTION = "projectProcessDescription";
        public static final String I_BACK                        = "back";
        public static final String I_MODIFY                      = "modify";
        public static final String I_ADD_NEW_TASK                = "addNewTask";

    }

    public static class B_PROJECT_TASKS_TOOLBAR
    {
        public static final String ID        = "ProjectTasksToolbar";
        public static final String I_ADD_NEW = "addNew";

    }

    public static class B_PROJECT_TASKS
    {
        public static final String ID                  = "ProjectTasks";
        public static final String I_ID                = "id";
        public static final String I_CPR_ID            = "cprId";
        public static final String I_NOTES             = "notes";
        public static final String I_NAME              = "name";
        public static final String I_PAY_RATE          = "payRate";
        public static final String I_INVOICEABLE       = "invoiceable";
        public static final String I_INVOICEABLE_IMAGE = "invoiceableImage";
        public static final String I_FIX_PRICE         = "fixPrice";
        public static final String I_USER_ID           = "userId";
        public static final String I_STATUS            = "status";
        public static final String I_MESSAGE_LABEL     = "messageLabel";
        public static final String I_DELETE            = "delete";
        public static final String I_EDIT              = "edit";

    }

    public static class B_OPEN_PROJECT_ITEMS
    {
        public static final String ID                        = "OpenProjectItems";
        public static final String I_PROJECT_ID              = "projectId";
        public static final String I_TASK_ID                 = "taskId";
        public static final String I_PROJECT_NAME            = "projectName";
        public static final String I_TASK_NAME               = "taskName";
        public static final String I_TE_MONTH                = "teMonth";
        public static final String I_TE_YEAR                 = "teYear";
        public static final String I_TE_LAST_DAY             = "teLastDay";
        public static final String I_TE_FIRST_DAY            = "teFirstDay";
        public static final String I_WORK_HOURS              = "workHours";
        public static final String I_CREATE_INVOICE_POSITION = "createInvoicePosition";

    }

    public static class B_OPEN_PROJECT_ITEMS_CONTROL
    {
        public static final String ID            = "OpenProjectItemsControl";
        public static final String I_DESCRIPTION = "description";

    }

    public static class B_NEW_INVOICE_ITEM
    {
        public static final String ID             = "NewInvoiceItem";
        public static final String I_DELETE       = "delete";
        public static final String I_PERIOD_LABEL = "periodLabel";
        public static final String I_PERIOD_FROM  = "periodFrom";
        public static final String I_PERIOD_TO    = "periodTo";
        public static final String I_STATUS_LABEL = "statusLabel";
        public static final String I_STATUS       = "status";
        public static final String I_TEXT         = "text";

    }

    public static class B_PLANNED_PROJECT_ITEMS
    {
        public static final String ID                        = "PlannedProjectItems";
        public static final String I_INVP_ID                 = "invpId";
        public static final String I_PROJECT_ID              = "projectId";
        public static final String I_TASK_ID                 = "taskId";
        public static final String I_PROJECT_NAME            = "projectName";
        public static final String I_TASK_NAME               = "taskName";
        public static final String I_TE_MONTH                = "teMonth";
        public static final String I_TE_YEAR                 = "teYear";
        public static final String I_TE_LAST_DAY             = "teLastDay";
        public static final String I_TE_FIRST_DAY            = "teFirstDay";
        public static final String I_WORK_HOURS              = "workHours";
        public static final String I_CREATE_INVOICE_POSITION = "createInvoicePosition";
        public static final String I_DELETE                  = "delete";

    }

    public static class B_OPEN_ITEMS
    {
        public static final String ID              = "OpenItems";
        public static final String I_HEADER_NUMBER = "headerNumber";
        public static final String I_CUSTOMER_NAME = "customerName";
        public static final String I_CUSTOMER_ID   = "customerId";
        public static final String I_PROJECT_ID    = "projectId";
        public static final String I_TASK_ID       = "taskId";
        public static final String I_PROJECT_NAME  = "projectName";
        public static final String I_TASK_NAME     = "taskName";
        public static final String I_DISPLAY_VALUE = "displayValue";

    }

    public static class L_VAT_RATE
    {
        public static final String ID      = "VatRate";
        public static final String I_NOTES = "notes";
        public static final String I_RATE  = "rate";
        public static final String I_NAME  = "name";
        public static final String I_ID    = "id";

    }

    public static class L_CUSTOMER
    {
        public static final String ID          = "Customer";
        public static final String I_ID        = "id";
        public static final String I_ADDRESS   = "address";
        public static final String I_NAME      = "name";
        public static final String I_POST_CODE = "postCode";
        public static final String I_TOWN      = "town";
        public static final String I_COUNTRY   = "country";

    }

    public static class L_SALUTATIONS
    {
        public static final String ID      = "Salutations";
        public static final String I_VALUE = "value";
        public static final String I_ID    = "id";

    }

    public static class L_CURRENCIES
    {
        public static final String ID        = "Currencies";
        public static final String I_CODE    = "code";
        public static final String I_USER_ID = "userId";
        public static final String I_NAME    = "name";
        public static final String I_ID      = "id";

    }

    public static class L_PROJECT_STATUS
    {
        public static final String ID            = "ProjectStatus";
        public static final String I_ORDER_KEY   = "orderKey";
        public static final String I_DESCRIPTION = "description";
        public static final String I_USER_ID     = "userId";
        public static final String I_ID          = "id";
        public static final String I_NAME        = "name";

    }

    public static class L_TASK_STATUS
    {
        public static final String ID                     = "TaskStatus";
        public static final String I_ORDER_KEY            = "orderKey";
        public static final String I_USER_ID              = "userId";
        public static final String I_DESCRIPTION          = "description";
        public static final String I_ID                   = "id";
        public static final String I_INVOICEABLE          = "invoiceable";
        public static final String I_NAME                 = "name";
        public static final String I_ASSIGN_AFTER_INVOICE = "assignAfterInvoice";

    }

    public static final String C_PROJECTS_STACK = "ProjectsStack";

    public static class C_PROJECTS_STACK_PAGES
    {
        public static final String PROJECTS = "Projects";
        public static final String DETAILS  = "Details";

    }

    public static final String C_PROJECTS_TAB = "ProjectsTab";

    public static class C_PROJECTS_TAB_PAGES
    {
        public static final String PROJECTS   = "projects";
        public static final String OPEN_ITEMS = "openItems";

    }

    public static final String C_PROJECTS_TOOLBAR = "ProjectsToolbar";
    public static final String C_PROJECTS         = "Projects";
    public static final String C_OPEN_ITEMS       = "OpenItems";
    public static final String C_PROJECTS_DETAIL  = "ProjectsDetail";
    public static final String C_DETAILS_TAB      = "DetailsTab";

    public static class C_DETAILS_TAB_PAGES
    {
        public static final String OPEN_ITEMS            = "OpenItems";
        public static final String PLANNED_PROJECT_ITEMS = "PlannedProjectItems";
        public static final String PROJECT_TASKS         = "ProjectTasks";

    }

    public static final String C_OPEN_PROJECT_ITEMS         = "OpenProjectItems";
    public static final String C_OPEN_PROJECT_ITEMS_CONTROL = "OpenProjectItemsControl";
    public static final String C_PLANNED_PROJECT_ITEMS      = "PlannedProjectItems";
    public static final String C_PROJECT_TASKS_TOOLBAR      = "ProjectTasksToolbar";
    public static final String C_PROJECT_TASKS              = "ProjectTasks";
    public static final String C_NEW_INVOICE_ITEM_POPUP     = "NewInvoiceItemPopup";
    public static final String C_NEW_INVOICE_ITEM           = "NewInvoiceItem";

    public static final String AC_ADD_NEW_TASK              = "ADD_NEW_TASK";
    public static final String AC_ADD_TO_INV_POS            = "ADD_TO_INV_POS";
    public static final String AC_APPROVE_INV_POS           = "APPROVE_INV_POS";
    public static final String AC_BACK_TO_PROJECT_OVERVIEW  = "BACK_TO_PROJECT_OVERVIEW";
    public static final String AC_CREATE_INVOICE_POSITION   = "CREATE_INVOICE_POSITION";
    public static final String AC_CREATE_NEW_PROJECT        = "CREATE_NEW_PROJECT";
    public static final String AC_DELETE_PLANNED_ITEM       = "DELETE_PLANNED_ITEM";
    public static final String AC_DELETE_PROJECT_TASK       = "DELETE_PROJECT_TASK";
    public static final String AC_EDIT_PROJECT_TASK         = "EDIT_PROJECT_TASK";
    public static final String AC_INVOICEABLE               = "INVOICEABLE";
    public static final String AC_INVOICEABLE_TASK          = "INVOICEABLE_TASK";
    public static final String AC_MODIFY_PROJECT            = "MODIFY_PROJECT";
    public static final String AC_OPEN_CUSTOMER             = "OPEN_CUSTOMER";
    public static final String AC_OPEN_ITEM                 = "OPEN_ITEM";
    public static final String AC_PROJECT_DETAILS           = "PROJECT_DETAILS";

}