package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_SALUTATIONS
{
    public static final String ID = "Salutations";

    public static class B_SALUTATIONS_TOOLBAR
    {
        public static final String ID                        = "SalutationsToolbar";
        public static final String I_ADD_NEW_SALUTATION_TYPE = "addNewSalutationType";

    }

    public static class B_SALUTATIONS
    {
        public static final String ID             = "Salutations";
        public static final String I_VALUE        = "value";
        public static final String I_ID           = "id";
        public static final String I_COMPANY_ID   = "companyId";
        public static final String I_DELETE       = "delete";
        public static final String I_EDIT         = "edit";
        public static final String I_DISPLAY_TEXT = "displayText";

    }

    public static class B_SALUTATIONS_EDIT
    {
        public static final String ID            = "SalutationsEdit";
        public static final String I_VALUE       = "value";
        public static final String I_PAGE_TITLE  = "pageTitle";
        public static final String I_VALUE_ERROR = "valueError";
        public static final String I_SAVE        = "save";
        public static final String I_CANCEL      = "cancel";
        public static final String I_ID          = "id";

    }

    public static class B_SALUTATIONS_INSERT
    {
        public static final String ID            = "SalutationsInsert";
        public static final String I_VALUE       = "value";
        public static final String I_PAGE_TITLE  = "pageTitle";
        public static final String I_VALUE_ERROR = "valueError";
        public static final String I_SAVE        = "save";
        public static final String I_CANCEL      = "cancel";

    }

    public static final String C_MAIN_STACK = "mainStack";

    public static class C_MAIN_STACK_PAGES
    {
        public static final String MAIN   = "main";
        public static final String EDIT   = "edit";
        public static final String INSERT = "insert";

    }

    public static final String C_SALUTATION_TOOLBAR = "SalutationToolbar";
    public static final String C_SALUTATIONS        = "Salutations";
    public static final String C_SALUTATIONS_EDIT   = "SalutationsEdit";
    public static final String C_SALUTATIONS_INSERT = "SalutationsInsert";

    public static final String AC_CREATE_SALUTATION = "CREATE_SALUTATION";
    public static final String AC_DELETE_SALUTATION = "DELETE_SALUTATION";
    public static final String AC_EDIT_CANCEL       = "EDIT_CANCEL";
    public static final String AC_EDIT_SAVE         = "EDIT_SAVE";
    public static final String AC_INSERT_CANCEL     = "INSERT_CANCEL";
    public static final String AC_INSERT_SAVE       = "INSERT_SAVE";
    public static final String AC_MODIFY_SALUTATION = "MODIFY_SALUTATION";

}