package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_TEST
{
    public static final String ID = "test";

    public static class B_TEST
    {
        public static final String ID = "test";

    }

    public static final String C_TEST = "test";

}