package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_TIME_ENTRY_OVERVIEW
{
    public static final String ID = "TimeEntryOverview";

    public static class B_USER_TOTAL_HOURS_FILTER
    {
        public static final String ID              = "userTotalHoursFilter";
        public static final String I_DATE_FROM     = "dateFrom";
        public static final String I_DATE_TO       = "dateTo";
        public static final String I_REFRESH_IMAGE = "refreshImage";
        public static final String I_USER_ID       = "userId";

    }

    public static class B_USER_TOTAL_HOURS
    {
        public static final String ID             = "userTotalHours";
        public static final String I_HEADER_CODE  = "headerCode";
        public static final String I_HOURS        = "hours";
        public static final String I_DESCRIPTION  = "description";
        public static final String I_USER_ID      = "userId";
        public static final String I_DATE_FROM    = "dateFrom";
        public static final String I_DATE_TO      = "dateTo";
        public static final String I_DISPLAY_TEXT = "displayText";

    }

    public static class B_USER_TOTAL_HOURS_OVERVIEW
    {
        public static final String ID                    = "userTotalHoursOverview";
        public static final String I_HEADER_CODE         = "headerCode";
        public static final String I_HOURS               = "hours";
        public static final String I_USER_ID             = "userId";
        public static final String I_DATE_FROM           = "dateFrom";
        public static final String I_DATE_TO             = "dateTo";
        public static final String I_WORK_PERIOD         = "workPeriod";
        public static final String I_PROJECT_DESCRIPTION = "projectDescription";
        public static final String I_WORK_DESCRIPTION    = "workDescription";
        public static final String I_WORK_DATE           = "workDate";
        public static final String I_DISPLAY_TEXT        = "displayText";

    }

    public static class L_USERS
    {
        public static final String ID                = "Users";
        public static final String I_PASSWORD        = "password";
        public static final String I_NOTES           = "notes";
        public static final String I_TOWN            = "town";
        public static final String I_LOCALE_COUNTRY  = "localeCountry";
        public static final String I_LAST_NAME       = "lastName";
        public static final String I_ADDRESS         = "address";
        public static final String I_ACTIVE          = "active";
        public static final String I_POST_CODE       = "postCode";
        public static final String I_LOCALE_LANGUAGE = "localeLanguage";
        public static final String I_ID              = "id";
        public static final String I_ROLE            = "role";
        public static final String I_COMPANY_ID      = "companyId";
        public static final String I_FIRST_NAME      = "firstName";
        public static final String I_EMAIL           = "email";

    }

    public static final String C_USER_TOTAL_HOURS_FILTER   = "userTotalHoursFilter";
    public static final String C_RESULTS                   = "results";
    public static final String C_RESULTS_SPLIT             = "resultsSplit";
    public static final String C_TOTAL_HOURS               = "totalHours";
    public static final String C_USER_TOTAL_HOURS_OVERVIEW = "userTotalHoursOverview";

    public static final String AC_REFRESH_USER_TOTAL_HOURS = "REFRESH_USER_TOTAL_HOURS";

    public static final String P_IN_EDIT_MODE              = "IN_EDIT_MODE";

}