package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_TIME_ENTRY
{
    public static final String ID = "TimeEntry";

    public static class B_COMPANY
    {
        public static final String ID                    = "Company";
        public static final String I_POST_CODE           = "postCode";
        public static final String I_ADDRESS_LINE_2      = "addressLine2";
        public static final String I_BANK_ADDRESS_LINE_2 = "bankAddressLine2";
        public static final String I_ACCOUNT_NUMBER      = "accountNumber";
        public static final String I_ADDRESS_LINE_1      = "addressLine1";
        public static final String I_BANK_ADDRESS_LINE_1 = "bankAddressLine1";
        public static final String I_BANK_POST_CODE      = "bankPostCode";
        public static final String I_IBAN                = "iban";
        public static final String I_ID                  = "id";
        public static final String I_ADDRESS_LINE_3      = "addressLine3";
        public static final String I_USER_ID             = "userId";
        public static final String I_BANK_TOWN           = "bankTown";
        public static final String I_NAME                = "name";
        public static final String I_TOWN                = "town";
        public static final String I_COUNTRY             = "country";
        public static final String I_BANK_NAME           = "bankName";
        public static final String I_BANK_COUNTRY        = "bankCountry";
        public static final String I_VAT_NR              = "vatNr";
        public static final String I_BANK_ADDRESS_LINE_3 = "bankAddressLine3";
        public static final String I_LOGO                = "logo";
        public static final String I_ADDRESS             = "address";

    }

    public static class B_TIME_ENTRY_ENTRY
    {
        public static final String ID                         = "TimeEntryEntry";
        public static final String I_WORK_DATE                = "workDate";
        public static final String I_START_TIME               = "startTime";
        public static final String I_END_TIME                 = "endTime";
        public static final String I_PROJECT                  = "project";
        public static final String I_PROCESS                  = "process";
        public static final String I_HOURS                    = "hours";
        public static final String I_START_LABEL              = "startLabel";
        public static final String I_END_LABEL                = "endLabel";
        public static final String I_HOURS_LABEL              = "hoursLabel";
        public static final String I_EQUALS_LABEL             = "equalsLabel";
        public static final String I_NOTES                    = "notes";
        public static final String I_ADD__ENTRY               = "Add Entry";
        public static final String I_EDIT_COMPANY_INFORMATION = "editCompanyInformation";
        public static final String I_PROJECT_LABEL            = "projectLabel";
        public static final String I_PROCESS_LABEL            = "processLabel";

    }

    public static class B_TIME_ENTRY
    {
        public static final String ID                 = "TimeEntry";
        public static final String I_ID               = "id";
        public static final String I_START_TIME       = "startTime";
        public static final String I_END_TIME         = "endTime";
        public static final String I_WORK_DESCRIPTION = "workDescription";
        public static final String I_CUPP_ID          = "cuppId";
        public static final String I_USER_ID          = "userId";
        public static final String I_WORK_DATE        = "workDate";
        public static final String I_HOURS_WORKED     = "hoursWorked";
        public static final String I_PROJECT          = "project";
        public static final String I_PROCESS          = "process";

    }

    public static class B_TIME_ENTRY_PAID
    {
        public static final String ID                 = "TimeEntryPaid";
        public static final String I_END_TIME         = "endTime";
        public static final String I_ID               = "id";
        public static final String I_START_TIME       = "startTime";
        public static final String I_WORK_DESCRIPTION = "workDescription";
        public static final String I_CUPP_ID          = "cuppId";
        public static final String I_USER_ID          = "userId";
        public static final String I_WORK_DATE        = "workDate";
        public static final String I_HOURS            = "hours";
        public static final String I_PROJECT          = "project";

    }

    public static class B_PROJECTS_TOOLBAR
    {
        public static final String ID                   = "ProjectsToolbar";
        public static final String I_CREATE_NEW_PROJECT = "createNewProject";

    }

    public static class B_PROJECTS
    {
        public static final String ID                            = "Projects";
        public static final String I_ID                          = "id";
        public static final String I_DESCRIPTION                 = "description";
        public static final String I_NAME                        = "name";
        public static final String I_STATUS                      = "status";
        public static final String I_USER_ID                     = "userId";
        public static final String I_CUSTOMER_ID                 = "customerId";
        public static final String I_START_DATE                  = "startDate";
        public static final String I_END_DATE                    = "endDate";
        public static final String I_NOTES                       = "notes";
        public static final String I_PROCESS_CPR_ID              = "processCprId";
        public static final String I_PROCESS_NOTES               = "processNotes";
        public static final String I_PROCESS_NAME                = "processName";
        public static final String I_PROCESS_PAY_RATE            = "processPayRate";
        public static final String I_PROCESS_USER_ID             = "processUserId";
        public static final String I_PROCESS_VAT_ID              = "processVatId";
        public static final String I_VAT_NAME                    = "vatName";
        public static final String I_VAT_RATE                    = "vatRate";
        public static final String I_CUSTOMER_NAME               = "customerName";
        public static final String I_CUSTOMER_ADDRESS_1          = "customerAddress1";
        public static final String I_CUSTOMER_ADDRESS_2          = "customerAddress2";
        public static final String I_CUSTOMER_ADDRESS_3          = "customerAddress3";
        public static final String I_CUSTOMER_POST_CODE          = "customerPostCode";
        public static final String I_CUSTOMER_TOWN               = "customerTown";
        public static final String I_CUSTOMER_COUNTRY            = "customerCountry";
        public static final String I_PROJECT_PROCESS_DESCRIPTION = "projectProcessDescription";

    }

    public static class B_PROJECTS_DETAIL
    {
        public static final String ID                        = "ProjectsDetail";
        public static final String I_BACK                    = "back";
        public static final String I_EDIT                    = "edit";
        public static final String I_ID                      = "id";
        public static final String I_DESCRIPTION             = "description";
        public static final String I_NAME                    = "name";
        public static final String I_STATUS                  = "status";
        public static final String I_USER_ID                 = "userId";
        public static final String I_CUSTOMER_ID             = "customerId";
        public static final String I_START_DATE              = "startDate";
        public static final String I_END_DATE                = "endDate";
        public static final String I_NOTES                   = "notes";
        public static final String I_CUSTOMER_NAME           = "customerName";
        public static final String I_CUSTOMER_ADDRESS_LINE_1 = "customerAddressLine1";
        public static final String I_CUSTOMER_ADDRESS_LINE_2 = "customerAddressLine2";
        public static final String I_CUSTOMER_ADDRESS_LINE_3 = "customerAddressLine3";
        public static final String I_CUSTOMER_POST_CODE      = "customerPostCode";
        public static final String I_CUSTOMER_TOWN           = "customerTown";
        public static final String I_CUSTOMER_COUNTRY        = "customerCountry";
        public static final String I_ADD_NEW_PROCESS         = "addNewProcess";

    }

    public static class B_PROJECT_PROCESS
    {
        public static final String ID         = "ProjectProcess";
        public static final String I_ID       = "id";
        public static final String I_CPR_ID   = "cprId";
        public static final String I_NOTES    = "notes";
        public static final String I_NAME     = "name";
        public static final String I_PAY_RATE = "payRate";
        public static final String I_USER_ID  = "userId";
        public static final String I_VAT_ID   = "vatId";
        public static final String I_VAT_NAME = "vatName";
        public static final String I_VAT_RATE = "vatRate";

    }

    public static class B_CUSTOMERS_TOOLBAR
    {
        public static final String ID                    = "CustomersToolbar";
        public static final String I_CREATE_NEW_CUSTOMER = "createNewCustomer";

    }

    public static class B_CUSTOMERS
    {
        public static final String ID                 = "Customers";
        public static final String I_USER_ID          = "userId";
        public static final String I_ID               = "id";
        public static final String I_ADDRESS_LINE_1   = "addressLine1";
        public static final String I_ADDRESS_LINE_2   = "addressLine2";
        public static final String I_NAME             = "name";
        public static final String I_POST_CODE        = "postCode";
        public static final String I_ADDRESS_LINE_3   = "addressLine3";
        public static final String I_TOWN             = "town";
        public static final String I_COUNTRY          = "country";
        public static final String I_EMAIL            = "email";
        public static final String I_PHONE            = "phone";
        public static final String I_CONTACT_TYPES_ID = "contactTypesId";
        public static final String I_SALUTATIONS_ID   = "salutationsId";
        public static final String I_CUSTOMER_ID      = "customerId";
        public static final String I_FIRST_NAME       = "firstName";
        public static final String I_LAST_NAME        = "lastName";
        public static final String I_MOBILE           = "mobile";

    }

    public static class L_VAT_RATE
    {
        public static final String ID      = "VatRate";
        public static final String I_NOTES = "notes";
        public static final String I_RATE  = "rate";
        public static final String I_NAME  = "name";
        public static final String I_ID    = "id";

    }

    public static class L_CUSTOMER
    {
        public static final String ID               = "Customer";
        public static final String I_ID             = "id";
        public static final String I_ADDRESS_LINE_1 = "addressLine1";
        public static final String I_ADDRESS_LINE_2 = "addressLine2";
        public static final String I_NAME           = "name";
        public static final String I_POST_CODE      = "postCode";
        public static final String I_ADDRESS_LINE_3 = "addressLine3";
        public static final String I_TOWN           = "town";
        public static final String I_COUNTRY        = "country";

    }

    public static class L_CUSTOMER_PROJECTS
    {
        public static final String ID            = "CustomerProjects";
        public static final String I_NAME        = "name";
        public static final String I_ID          = "id";
        public static final String I_CUST_ID     = "custId";
        public static final String I_DESCRIPTION = "description";

    }

    public static class L_CUSTOMER_PROJECT_PROCESSES
    {
        public static final String ID             = "CustomerProjectProcesses";
        public static final String I_ID           = "id";
        public static final String I_CPR_ID       = "cprId";
        public static final String I_NOTES        = "notes";
        public static final String I_PROJECT_NAME = "projectName";
        public static final String I_PROCESS_NAME = "processName";
        public static final String I_PAY_RATE     = "payRate";
        public static final String I_USER_ID      = "userId";
        public static final String I_VAT_ID       = "vatId";
        public static final String I_VAT_RATE     = "vatRate";

    }

    public static class L_CONTACT_TYPES
    {
        public static final String ID            = "ContactTypes";
        public static final String I_TYPE        = "type";
        public static final String I_ID          = "id";
        public static final String I_DESCRIPTION = "description";

    }

    public static class L_SALUTATIONS
    {
        public static final String ID      = "Salutations";
        public static final String I_VALUE = "value";
        public static final String I_ID    = "id";

    }

    public static final String C_COMPANY = "Company";
    public static final String C_MAIN    = "Main";

    public static class C_MAIN_PAGES
    {
        public static final String TIME__ENTRY          = "Time Entry";
        public static final String PROJECTS             = "Projects";
        public static final String CUSTOMERS            = "Customers";
        public static final String MASTER__DATA         = "Master Data";
        public static final String COMPANY__INFORMATION = "Company Information";

    }

    public static final String C_TIME_ENTRY_ENTRY = "TimeEntryEntry";
    public static final String C_ENTRIES          = "Entries";

    public static class C_ENTRIES_PAGES
    {
        public static final String UNPAID = "Unpaid";
        public static final String PAID   = "Paid";

    }

    public static final String C_TIME_ENTRY      = "TimeEntry";
    public static final String C_TIME_ENTRY_PAID = "TimeEntryPaid";
    public static final String C_PROJECTS_STACK  = "ProjectsStack";

    public static class C_PROJECTS_STACK_PAGES
    {
        public static final String PROJECTS = "Projects";
        public static final String PROCESS  = "Process";

    }

    public static final String C_PROJECTS_TOOLBAR = "ProjectsToolbar";
    public static final String C_PROJECTS         = "Projects";
    public static final String C_PROJECTS_DETAIL  = "ProjectsDetail";
    public static final String C_PROJECT_PROCESS  = "ProjectProcess";
    public static final String C_CUSTOMER_STACK   = "CustomerStack";

    public static class C_CUSTOMER_STACK_PAGES
    {
        public static final String CUSTOMER_OVERVIEW = "CustomerOverview";
        public static final String CUSTOMER_DETAILS  = "CustomerDetails";

    }

    public static final String C_CUSTOMERS_TOOLBAR         = "CustomersToolbar";
    public static final String C_CUSTOMER                  = "Customer";
    public static final String C_CUSTOMER_DETAILS_FORM     = "CustomerDetailsForm";
    public static final String C_MASTER_DATA_CANVAS        = "masterDataCanvas";
    public static final String C_COMPANY_EDIT_SCREEN       = "CompanyEditScreen";

    public static final String AC_ADD_NEW_PROCESS          = "ADD_NEW_PROCESS";
    public static final String AC_ADD_TIME_ENTRY           = "ADD_TIME_ENTRY";
    public static final String AC_BACK_TO_PROJECT_OVERVIEW = "BACK_TO_PROJECT_OVERVIEW";
    public static final String AC_CREATE_NEW_CUSTOMER      = "CREATE_NEW_CUSTOMER";
    public static final String AC_CREATE_NEW_PROJECT       = "CREATE_NEW_PROJECT";
    public static final String AC_DELETE_PROCESS           = "DELETE_PROCESS";
    public static final String AC_DELETE_TIME_ENTRY        = "DELETE_TIME_ENTRY";
    public static final String AC_EDIT_TIME_ENTRY          = "EDIT_TIME_ENTRY";
    public static final String AC_MODIFY_PROCESS           = "MODIFY_PROCESS";
    public static final String AC_MODIFY_PROJECT           = "MODIFY_PROJECT";
    public static final String AC_OPEN_CUSTOMER            = "OPEN_CUSTOMER";
    public static final String AC_PROJECT_DETAILS          = "PROJECT_DETAILS";
    public static final String AC_SHOW_CUSTOMER_DETAILS    = "SHOW_CUSTOMER_DETAILS";

}