package org.entirej.ejinvoice.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_TIME_ENTRY
{
    public static final String ID = "TimeEntry";

    public static class B_COMPANY
    {
        public static final String ID                = "Company";
        public static final String I_POST_CODE       = "postCode";
        public static final String I_ADDRESS         = "address";
        public static final String I_ID              = "id";
        public static final String I_NAME            = "name";
        public static final String I_TOWN            = "town";
        public static final String I_COUNTRY         = "country";
        public static final String I_VAT_NR          = "vatNr";
        public static final String I_LOGO            = "logo";
        public static final String I_DISPLAY_ADDRESS = "displayAddress";

    }

    public static class B_TIME_ENTRY_ENTRY
    {
        public static final String ID                         = "TimeEntryEntry";
        public static final String I_WORK_DATE                = "workDate";
        public static final String I_START_TIME               = "startTime";
        public static final String I_END_TIME                 = "endTime";
        public static final String I_PROJECT                  = "project";
        public static final String I_TASK                     = "task";
        public static final String I_HOURS                    = "hours";
        public static final String I_START_LABEL              = "startLabel";
        public static final String I_END_LABEL                = "endLabel";
        public static final String I_HOURS_LABEL              = "hoursLabel";
        public static final String I_EQUALS_LABEL             = "equalsLabel";
        public static final String I_NOTES                    = "notes";
        public static final String I_ADD_ENTRY                = "Add Entry";
        public static final String I_EDIT_COMPANY_INFORMATION = "editCompanyInformation";
        public static final String I_PROJECT_LABEL            = "projectLabel";
        public static final String I_PROCESS_LABEL            = "processLabel";
        public static final String I_REFRESH_PROJECT_LISTS    = "refreshProjectLists";

    }

    public static class B_TIME_ENTRY
    {
        public static final String ID                 = "TimeEntry";
        public static final String I_ID               = "id";
        public static final String I_COMPANY_ID       = "companyId";
        public static final String I_START_TIME       = "startTime";
        public static final String I_END_TIME         = "endTime";
        public static final String I_WORK_DESCRIPTION = "workDescription";
        public static final String I_CUPT_ID          = "cuptId";
        public static final String I_CUPR_ID          = "cuprId";
        public static final String I_USER_ID          = "userId";
        public static final String I_WORK_DATE        = "workDate";
        public static final String I_HOURS_WORKED     = "hoursWorked";
        public static final String I_PROJECT          = "project";
        public static final String I_TASK             = "task";
        public static final String I_START_LABEL      = "startLabel";
        public static final String I_END_LABEL        = "endLabel";
        public static final String I_HOURS_LABEL      = "hoursLabel";
        public static final String I_EQUALS_LABEL     = "equalsLabel";
        public static final String I__EDIT            = "_edit";
        public static final String I__DELETE          = "_delete";
        public static final String I_INVP_ID          = "invpId";

    }

    public static class B_MENU
    {
        public static final String ID               = "menu";
        public static final String I_PARENT_ID      = "parentId";
        public static final String I_ID             = "id";
        public static final String I_NAME           = "name";
        public static final String I_ICON_NAME      = "iconName";
        public static final String I_ACTION_COMMAND = "actionCommand";
        public static final String I_ICON           = "icon";

    }

    public static class L_VAT_RATE
    {
        public static final String ID           = "VatRate";
        public static final String I_NOTES      = "notes";
        public static final String I_RATE       = "rate";
        public static final String I_NAME       = "name";
        public static final String I_ID         = "id";
        public static final String I_COMPANY_ID = "companyId";

    }

    public static class L_CUSTOMER
    {
        public static final String ID                 = "Customer";
        public static final String I_ID               = "id";
        public static final String I_ADDRESS          = "address";
        public static final String I_NAME             = "name";
        public static final String I_POST_CODE        = "postCode";
        public static final String I_TOWN             = "town";
        public static final String I_COUNTRY          = "country";
        public static final String I_COMPANY_ID       = "companyId";
        public static final String I_ITEMS_TO_INVOICE = "itemsToInvoice";

    }

    public static class L_CUSTOMER_PROJECTS
    {
        public static final String ID              = "CustomerProjects";
        public static final String I_NAME          = "name";
        public static final String I_ID            = "id";
        public static final String I_CUSTOMER_ID   = "customerId";
        public static final String I_CUSTOMER_NAME = "customerName";
        public static final String I_DESCRIPTION   = "description";
        public static final String I_COMPANY_ID    = "companyId";
        public static final String I_STATUS        = "status";
        public static final String I_FIX_PRICE     = "fixPrice";
        public static final String I_DISPLAY_NAME  = "displayName";

    }

    public static class L_CONTACT_TYPES
    {
        public static final String ID            = "ContactTypes";
        public static final String I_TYPE        = "type";
        public static final String I_ID          = "id";
        public static final String I_DESCRIPTION = "description";
        public static final String I_COMPANY_ID  = "companyId";

    }

    public static class L_SALUTATIONS
    {
        public static final String ID           = "Salutations";
        public static final String I_VALUE      = "value";
        public static final String I_ID         = "id";
        public static final String I_COMPANY_ID = "companyId";

    }

    public static class L_UPDATE_CUSTOMER_PROJECT_TASKS
    {
        public static final String ID                    = "UpdateCustomerProjectTasks";
        public static final String I_ID                  = "id";
        public static final String I_CPR_ID              = "cprId";
        public static final String I_NOTES               = "notes";
        public static final String I_PROJECT_DESCRIPTION = "projectDescription";
        public static final String I_PROJECT_NAME        = "projectName";
        public static final String I_TASK_NAME           = "taskName";
        public static final String I_PAY_RATE            = "payRate";
        public static final String I_COMPANY_ID          = "companyId";
        public static final String I_STATUS              = "status";

    }

    public static class L_CUSTOMER_PROJECT_TASKS
    {
        public static final String ID                    = "CustomerProjectTasks";
        public static final String I_ID                  = "id";
        public static final String I_CPR_ID              = "cprId";
        public static final String I_NOTES               = "notes";
        public static final String I_PROJECT_DESCRIPTION = "projectDescription";
        public static final String I_PROJECT_NAME        = "projectName";
        public static final String I_TASK_NAME           = "taskName";
        public static final String I_PAY_RATE            = "payRate";
        public static final String I_COMPANY_ID          = "companyId";
        public static final String I_STATUS              = "status";

    }

    public static class L_PROJECT_STATUS
    {
        public static final String ID            = "ProjectStatus";
        public static final String I_DESCRIPTION = "description";
        public static final String I_NAME        = "name";
        public static final String I_CODE        = "code";

    }

    public static class L_TASK_STATUS
    {
        public static final String ID            = "TaskStatus";
        public static final String I_DESCRIPTION = "description";
        public static final String I_NAME        = "name";
        public static final String I_CODE        = "code";

    }

    public static class L_CUSTOMER_LOCALE
    {
        public static final String ID              = "CustomerLocale";
        public static final String I_LANGUAGE      = "language";
        public static final String I_COUNTRY       = "country";
        public static final String I_LOCALE        = "locale";
        public static final String I_LANGUAGE_DESC = "languageDesc";
        public static final String I_COUNTRY_DESC  = "countryDesc";
        public static final String I_CCY_CODE      = "ccyCode";

    }

    public static class L_WORK_WEEK_PROJECT_TASKS
    {
        public static final String ID                    = "WorkWeekProjectTasks";
        public static final String I_ID                  = "id";
        public static final String I_CPR_ID              = "cprId";
        public static final String I_NOTES               = "notes";
        public static final String I_PROJECT_DESCRIPTION = "projectDescription";
        public static final String I_PROJECT_NAME        = "projectName";
        public static final String I_TASK_NAME           = "taskName";
        public static final String I_PAY_RATE            = "payRate";
        public static final String I_COMPANY_ID          = "companyId";
        public static final String I_STATUS              = "status";

    }

    public static class L_UPDATE_CUSTOMER_PROJECTS
    {
        public static final String ID              = "UpdateCustomerProjects";
        public static final String I_NAME          = "name";
        public static final String I_ID            = "id";
        public static final String I_CUSTOMER_ID   = "customerId";
        public static final String I_CUSTOMER_NAME = "customerName";
        public static final String I_DESCRIPTION   = "description";
        public static final String I_COMPANY_ID    = "companyId";
        public static final String I_STATUS        = "status";
        public static final String I_FIX_PRICE     = "fixPrice";
        public static final String I_DISPLAY_NAME  = "displayName";

    }

    public static final String C_COMPANY    = "Company";
    public static final String C_MAIN_SPLIT = "mainSplit";
    public static final String C_MENU_GROUP = "menuGroup";
    public static final String C_MENU       = "Menu";
    public static final String C_MAIN_STACK = "MainStack";

    public static class C_MAIN_STACK_PAGES
    {
        public static final String TIME_ENTRY           = "TimeEntry";
        public static final String TIME_ENTRY_OVERVIEW  = "TimeEntryOverview";
        public static final String PROJECTS             = "Projects";
        public static final String PROJECT_TASKS        = "ProjectTasks";
        public static final String INVOICE_CREATION     = "InvoiceCreation";
        public static final String CUSTOMER             = "Customer";
        public static final String CUSTOMER_CONTACTS    = "CustomerContacts";
        public static final String COMPANY              = "Company";
        public static final String INVOICE_PLANNING     = "InvoicePlanning";
        public static final String OUTSTANDING_INVOICES = "OutstandingInvoices";
        public static final String PAID_INVOICES        = "PaidInvoices";
        public static final String USERS                = "Users";
        public static final String CONTACT_TYPES        = "ContactTypes";
        public static final String SALUTATIONS          = "Salutations";
        public static final String VAT_RATES            = "VatRates";

    }

    public static final String C_TIME_ENTRY_ENTRY          = "TimeEntryEntry";
    public static final String C_TIME_ENTRY                = "TimeEntry";
    public static final String C_TIME_ENTRY_OVERVIEW_FORM  = "TimeEntryOverviewForm";
    public static final String C_PROJECT_FORM              = "ProjectForm";
    public static final String C_PROJECT_TASKS_FORM        = "ProjectTasksForm";
    public static final String C_INVOICE_CREATION_FORM     = "InvoiceCreationForm";
    public static final String C_CUSTOMER_FORM             = "CustomerForm";
    public static final String C_CUSTOMER_CONTACTS_FORM    = "CustomerContactsForm";
    public static final String C_COMPANY_FORM              = "CompanyForm";
    public static final String C_INVOICE_PLANNING_FORM     = "InvoicePlanningForm";
    public static final String C_OUTSTANDING_INVOICES_FORM = "OutstandingInvoicesForm";
    public static final String C_PAID_INVOICES_FORM        = "PaidInvoicesForm";
    public static final String C_USERS_FORM                = "UsersForm";
    public static final String C_CONTACT_TYPES_FORM        = "ContactTypesForm";
    public static final String C_SALUTATIONS_FORM          = "SalutationsForm";
    public static final String C_VAT_RATES_FORM            = "VatRatesForm";

    public static final String AC_ADD_TIME_ENTRY           = "ADD_TIME_ENTRY";
    public static final String AC_DELETE_TIME_ENTRY        = "DELETE_TIME_ENTRY";
    public static final String AC_EDIT_TIME_ENTRY          = "EDIT_TIME_ENTRY";
    public static final String AC_OPEN_MENU_ITEM           = "OPEN_MENU_ITEM";
    public static final String AC_REFRESH_PROJECT_LISTS    = "REFRESH_PROJECT_LISTS";

    public static final String P_IN_EDIT_MODE              = "IN_EDIT_MODE";

}