package org.entirej.ejinvoice.referencedlovdefs.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class RL_CUSTOMER_LOCALE {
	public static final String ID = "CustomerLocale";

	public static class L_CUSTOMER_LOCALE {
		public static final String ID = "CustomerLocale";
		public static final String I_LANGUAGE = "language";
		public static final String I_COUNTRY = "country";
		public static final String I_LOCALE = "locale";
		public static final String I_LANGUAGE_DESC = "languageDesc";
		public static final String I_COUNTRY_DESC = "countryDesc";
		public static final String I_CCY_CODE = "ccyCode";

	}

}