package org.entirej.ejinvoice.referencedlovdefs.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class RL_CURRENCIES
{
    public static final String ID = "Currencies";

    public static class L_CURRENCIES
    {
        public static final String ID           = "Currencies";
        public static final String I_CODE       = "code";
        public static final String I_COMPANY_ID = "companyId";
        public static final String I_NAME       = "name";
        public static final String I_ID         = "id";

    }

}