package org.entirej.ejinvoice.referencedlovdefs.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class RL_CUSTOMER_PROJECTS {
	public static final String ID = "CustomerProjects";

	public static class L_CUSTOMER_PROJECTS {
		public static final String ID = "CustomerProjects";
		public static final String I_NAME = "name";
		public static final String I_ID = "id";
		public static final String I_CUST_ID = "custId";
		public static final String I_DESCRIPTION = "description";
		public static final String I_COMPANY_ID = "companyId";

	}

}