package org.entirej.ejinvoice.referencedlovdefs.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class RL_CUSTOMER_PROJECT_TASKS
{
    public static final String ID = "CustomerProjectTasks";

    public static class L_CUSTOMER_PROJECT_TASKS
    {
        public static final String ID                    = "CustomerProjectTasks";
        public static final String I_ID                  = "id";
        public static final String I_CPR_ID              = "cprId";
        public static final String I_NOTES               = "notes";
        public static final String I_PROJECT_DESCRIPTION = "projectDescription";
        public static final String I_PROJECT_NAME        = "projectName";
        public static final String I_PROCESS_NAME        = "processName";
        public static final String I_PAY_RATE            = "payRate";
        public static final String I_COMPANY_ID          = "companyId";

    }

}