package org.entirej.ejinvoice.referencedlovdefs.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class RL_COMPANY_INFORMATION
{
    public static final String ID = "CompanyInformation";

    public static class L_COMPANY_INFORMATION
    {
        public static final String ID          = "CompanyInformation";
        public static final String I_NAME      = "name";
        public static final String I_TOWN      = "town";
        public static final String I_ADDRESS   = "address";
        public static final String I_ID        = "id";
        public static final String I_POST_CODE = "postCode";

    }

}