package org.entirej.ejinvoice.referencedlovdefs.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class RL_INITIAL_INVOICE_POSITION_STATUS
{
    public static final String ID = "initialInvoicePositionStatus";

    public static class L_INITIAL_INVOICE_POSITION_STATUS
    {
        public static final String ID       = "initialInvoicePositionStatus";
        public static final String I_NAME   = "name";
        public static final String I_STATUS = "status";

    }

}