package org.entirej.ejinvoice.referencedlovdefs.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class RL_TASK_STATUS
{
    public static final String ID = "TaskStatus";

    public static class L_TASK_STATUS
    {
        public static final String ID                     = "TaskStatus";
        public static final String I_ORDER_KEY            = "orderKey";
        public static final String I_USER_ID              = "userId";
        public static final String I_DESCRIPTION          = "description";
        public static final String I_ID                   = "id";
        public static final String I_INVOICEABLE          = "invoiceable";
        public static final String I_NAME                 = "name";
        public static final String I_ASSIGN_AFTER_INVOICE = "assignAfterInvoice";

    }

}