package org.entirej.ejinvoice.referencedlovdefs.constants;

/*
 * AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the entirej plugin from the form.
 * It should not be modified by hand.
 */
public class RL_USERS
{
    public static final String ID = "Users";

    public static class L_USERS
    {
        public static final String ID                = "Users";
        public static final String I_PASSWORD        = "password";
        public static final String I_NOTES           = "notes";
        public static final String I_TOWN            = "town";
        public static final String I_LOCALE_COUNTRY  = "localeCountry";
        public static final String I_LAST_NAME       = "lastName";
        public static final String I_ADDRESS         = "address";
        public static final String I_ACTIVE          = "active";
        public static final String I_POST_CODE       = "postCode";
        public static final String I_LOCALE_LANGUAGE = "localeLanguage";
        public static final String I_ID              = "id";
        public static final String I_ROLE            = "role";
        public static final String I_COMPANY_ID      = "companyId";
        public static final String I_FIRST_NAME      = "firstName";
        public static final String I_EMAIL           = "email";

    }

}