package org.entirej.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the EntireJProperties.  It
 * should not be modified by hand.
 */
public class EJ_PROPERTIES {
	public static final String M_DEFAULT = "Default";

	public static final String P_USER = "USER";
	public static final String P_EMAIL = "email";
	public static final String P_NAME = "name";

	public static final String VA_DATA = "data";
	public static final String VA_DATA_BOLD = "dataBold";
	public static final String VA_DESCRIPTION = "description";
	public static final String VA_TITLE = "title";
	public static final String VA_DATA_BOLD_150 = "dataBold150";
	public static final String VA_BOLD = "bold";

}