package org.entirej.ejinvoice.referencedlovdefs.constants;

/*
 * AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the entirej plugin from the form.
 * It should not be modified by hand.
 */
public class RL_SALUTATIONS
{
    public static final String ID = "Salutations";

    public static class L_SALUTATIONS
    {
        public static final String ID        = "Salutations";
        public static final String I_VALUE   = "value";
        public static final String I_ID      = "id";
        public static final String I_USER_ID = "userId";

    }

}