package org.entirej.ejinvoice.referencedlovdefs.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class RL_VAT_RATE
{
    public static final String ID = "VatRate";

    public static class L_VAT_RATE
    {
        public static final String ID        = "VatRate";
        public static final String I_USER_ID = "userId";
        public static final String I_RATE    = "rate";
        public static final String I_ID      = "id";
        public static final String I_NOTES   = "notes";
        public static final String I_NAME    = "name";

    }

}